<?php
require __DIR__.'/portal-lib.php';
$student=require_student();$studentId=(string)$student['Yuva Club ID'];$growth=null;
try{$growth=growth_profile_service()->forStudent($studentId);}catch(Throwable $error){error_log('YUVA My Growth unavailable correlation='.bin2hex(random_bytes(12)).' exception_type='.get_class($error));}
portal_header('My Growth',true);
?>
<link rel="stylesheet" href="assets/my-growth.css?v=1">
<main class="growth-page" id="my-growth-main">
  <a class="growth-back" href="portal.php">← Student dashboard</a>
  <header class="growth-hero"><p class="eyebrow">My Growth</p><h1>See what practice is building.</h1><p>Your private progress profile uses completed, comparable YUVA Club activity—never screen time or login counts.</p></header>
  <?php if(!is_array($growth)): ?><section class="growth-empty"><h2>Growth is temporarily unavailable</h2><p>Your records are safe. Please try again later.</p></section>
  <?php else: $summary=$growth['summary']; ?>
  <section class="growth-metrics" aria-label="Growth summary">
    <article><span>Leadership</span><strong><?php echo e((string)$summary['leadership_level']); ?></strong></article>
    <article><span>Challenges</span><strong><?php echo e((string)$summary['challenges_completed']); ?></strong></article>
    <article><span>Personal Bests</span><strong><?php echo e((string)$summary['personal_bests']); ?></strong></article>
    <article><span>Benchmarks Beaten</span><strong><?php echo e((string)$summary['benchmarks_beaten']); ?></strong></article>
    <article><span>Healthy Consistency</span><strong><?php echo e((string)$summary['consistency_weeks']); ?> weeks</strong><small><?php echo $summary['practice_this_week']?'Practice completed this week':'One meaningful activity completes this week'; ?></small></article>
  </section>
  <section class="growth-next"><p class="eyebrow">Next best action</p><h2><?php echo e((string)$growth['next_action']['text']); ?></h2><a class="button primary" href="<?php echo e((string)$growth['next_action']['href']); ?>">Take a challenge</a></section>
  <section><div class="growth-heading"><p class="eyebrow">Your Skills</p><h2>Transparent, compatible score trends</h2></div>
    <?php if($growth['skills']===[]): ?><div class="growth-empty"><h3>Your growth starts with practice</h3><p>Complete an AI-coached Quick Challenge to begin.</p></div><?php else: ?><div class="growth-skill-grid"><?php foreach($growth['skills'] as$skill): ?><article><h3><?php echo e(ucwords(str_replace('-',' ',(string)$skill['skill_code']))); ?></h3><strong><?php echo e((string)$skill['current']); ?></strong><?php if($skill['comparable']): ?><p>Previous <?php echo e((string)$skill['previous']); ?> · <b><?php echo ((int)$skill['change']>=0?'↑ +':'↓ ').e((string)$skill['change']); ?></b></p><?php else: ?><p>Complete another compatible challenge to see growth.</p><?php endif; ?><small>Best <?php echo e((string)$skill['best']); ?> · <?php echo e((string)$skill['attempts']); ?> comparable attempt(s)</small></article><?php endforeach; ?></div><?php endif; ?>
  </section>
  <section><div class="growth-heading"><p class="eyebrow">Recent comparable practice</p><h2>Growth trend</h2></div><?php if(count($growth['trend'])<2): ?><div class="growth-empty"><p>Complete another compatible challenge to establish a meaningful trend.</p></div><?php else: ?><ol class="growth-trend"><?php foreach(array_reverse($growth['trend'])as$point): ?><li><span><?php echo e((string)$point['label']); ?></span><strong><?php echo e((string)$point['score']); ?></strong></li><?php endforeach; ?></ol><?php endif; ?></section>
  <section class="growth-columns"><div><div class="growth-heading"><p class="eyebrow">Personal Bests</p><h2>Your best practice</h2></div><?php foreach($growth['personal_bests']as$best): ?><article class="growth-row"><span><?php echo e((string)$best['display_name']); ?></span><strong><?php echo e((string)$best['best_score']); ?></strong></article><?php endforeach; ?><?php if($growth['personal_bests']===[]): ?><p class="growth-empty">No Personal Best yet.</p><?php endif; ?></div><div><div class="growth-heading"><p class="eyebrow">Benchmarks</p><h2>Privacy-safe targets</h2></div><?php foreach(array_slice($growth['benchmarks'],0,6)as$benchmark): ?><article class="growth-row"><span><?php echo e((string)$benchmark['label']); ?></span><strong><?php echo $benchmark['beaten']?'Beaten ✓':e((string)$benchmark['points_to_go']).' points to go'; ?></strong></article><?php endforeach; ?><?php if($growth['benchmarks']===[]): ?><p class="growth-empty">Complete a scored challenge to see benchmark progress.</p><?php endif; ?></div></section>
  <section><div class="growth-heading"><p class="eyebrow">Achievements</p><h2>Milestones that mean something</h2></div><?php if($growth['achievements']===[]): ?><p class="growth-empty">Your first meaningful achievement is waiting.</p><?php else: ?><div class="growth-achievements"><?php foreach($growth['achievements']as$achievement): ?><article><span aria-hidden="true">🏆</span><h3><?php echo e((string)$achievement['display_name']); ?></h3><p><?php echo e((string)$achievement['description']); ?></p></article><?php endforeach; ?></div><?php endif; ?></section>
  <section class="growth-columns"><div><div class="growth-heading"><p class="eyebrow">AI Mentor connection</p><h2>Coached work</h2></div><p><strong><?php echo e((string)$growth['ai_mentor']['research_reviews']); ?></strong> applied research reviews · <strong><?php echo e((string)$growth['ai_mentor']['coached_presentations']); ?></strong> coached presentations</p><small>Only approved activity is summarized; provider details and hidden reasoning are never shown.</small></div><div><div class="growth-heading"><p class="eyebrow">Leadership Journey</p><h2>Approved level</h2></div><p><strong><?php echo e((string)$summary['leadership_level']); ?></strong></p><small>Practice scores and benchmark labels do not change Leadership eligibility.</small></div></section>
  <section><div class="growth-heading"><p class="eyebrow">Recent Growth</p><h2>Meaningful activity</h2></div><?php if($growth['recent_activity']===[]): ?><p class="growth-empty">Complete a challenge, reflection, AI Mentor review, or verified presentation to begin your history.</p><?php else: ?><ol class="growth-trend"><?php foreach($growth['recent_activity'] as$activity): ?><li><span><?php echo e((string)$activity['activity_type']); ?> · <?php echo e((string)$activity['label']); ?></span><time><?php echo e(substr((string)$activity['event_at'],0,10)); ?></time></li><?php endforeach; ?></ol><?php endif; ?></section>
  <?php endif; ?>
</main>
<?php portal_footer(); ?>
