<section class="form-card" id="quick-challenges">
  <p class="eyebrow">Phase 2C.2A</p><h2>Quick Challenge templates</h2>
  <p>Reusable, version-frozen asynchronous challenges. AI Challenge Scores are practice coaching only and never official Competition Scores.</p>
  <?php if($quickChallengeAdminNotice!==''): ?><div class="form-status success"><?php echo e($quickChallengeAdminNotice); ?></div><?php endif; ?>
  <?php if($quickChallengeAdminError!==''): ?><div class="form-status error" role="alert"><?php echo e($quickChallengeAdminError); ?></div><?php endif; ?>
  <?php if(($admin['role']??'')===YUVA_ROLE_MASTER_ADMIN): ?>
  <form action="admin-quick-challenge-action.php" method="post" class="form-card">
    <?php echo csrf_field(); ?><input type="hidden" name="action" value="create_template">
    <div class="field-grid"><label>Template code<input name="template_code" pattern="[a-z0-9][a-z0-9-]{2,79}" required></label><label>Name<input name="display_name" maxlength="160" required></label></div>
    <label>Type<select name="challenge_type" required><option value="speech">60-Second Speech</option><option value="persuasion">90-Second Persuasion</option><option value="impromptu">Impromptu Speaking</option><option value="explain">Explain It Simply</option><option value="storytelling">Storytelling</option><option value="elevator_pitch">Elevator Pitch</option><option value="critical_thinking">Critical Thinking / Opinion</option><option value="teaching">Teach Something</option><option value="research_summary">Research Summary</option><option value="leadership_reflection">Leadership Reflection</option></select></label>
    <label>Prompt<textarea name="prompt_text" maxlength="2000" required></textarea></label><label>Instructions<textarea name="instructions" maxlength="2000" required></textarea></label>
    <div class="field-grid"><label>Difficulty<select name="difficulty"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Prompt visibility<select name="prompt_reveal_mode"><option value="visible">Visible before start</option><option value="on_start">Reveal on Start Challenge</option></select></label></div>
    <div class="field-grid"><label>Preparation seconds<input type="number" name="preparation_seconds" min="0" max="600" value="30" required></label><label>Response seconds<input type="number" name="response_seconds" min="15" max="900" value="60" required></label><label>Attempts allowed<input type="number" name="maximum_attempts" min="1" max="20" value="3" required></label><label>Attempt policy<select name="attempt_policy"><option value="best">Best counts</option><option value="latest">Latest counts</option></select></label></div>
    <fieldset><legend>Skills</legend><?php foreach(['public-speaking'=>'Public Speaking','storytelling'=>'Storytelling','persuasion'=>'Persuasion','research'=>'Research','critical-thinking'=>'Critical Thinking','impromptu-speaking'=>'Impromptu Speaking','presentation-delivery'=>'Presentation Delivery','communication-clarity'=>'Communication Clarity','leadership'=>'Leadership','teaching'=>'Teaching'] as$code=>$label): ?><label><input type="checkbox" name="skills[]" value="<?php echo e($code); ?>" <?php echo $code==='public-speaking'?'checked':''; ?>> <?php echo e($label); ?></label><?php endforeach; ?></fieldset>
    <button class="button primary" type="submit">Create Frozen Template Version</button>
  </form>
  <?php endif; ?>
  <h3>Templates</h3><?php if($quickChallengeTemplates===[]): ?><p>No templates available.</p><?php endif; ?>
  <?php foreach($quickChallengeTemplates as$template): ?><article class="form-card"><h3><?php echo e((string)$template['display_name']); ?></h3><p><?php echo e((string)$template['difficulty']); ?> · <?php echo e((string)$template['skills']); ?> · <?php echo e((string)$template['response_seconds']); ?> seconds · <?php echo e((string)$template['maximum_attempts']); ?> attempts</p><p><strong><?php echo e((string)$template['status']); ?></strong> · Version <?php echo e((string)$template['version_number']); ?></p>
  <?php if(($admin['role']??'')===YUVA_ROLE_MASTER_ADMIN&&$template['status']==='Draft'): ?><form action="admin-quick-challenge-action.php" method="post"><?php echo csrf_field(); ?><input type="hidden" name="action" value="publish_template"><input type="hidden" name="template_guid" value="<?php echo e((string)$template['template_guid']); ?>"><input type="hidden" name="row_version" value="<?php echo e((string)$template['row_version']); ?>"><button class="button ghost">Publish Template</button></form><?php endif; ?><?php if(($admin['role']??'')===YUVA_ROLE_MASTER_ADMIN): ?><form action="admin-quick-challenge-action.php" method="post"><?php echo csrf_field(); ?><input type="hidden" name="action" value="configure_ai_scoring"><input type="hidden" name="version_guid" value="<?php echo e((string)$template['version_guid']); ?>"><label>AI practice scoring<select name="enabled"><option value="1">Enabled</option><option value="0">Disabled</option></select></label><label>Versioned scoring policy<select name="policy_code"><?php foreach($quickChallengePolicies as$policy): if($policy['challenge_type']!==$template['challenge_type']||$policy['status']!=='Active')continue; ?><option value="<?php echo e((string)$policy['policy_code']); ?>"><?php echo e((string)$policy['benchmark_label'].' · '.$policy['benchmark_score']); ?></option><?php endforeach; ?></select></label><button class="button ghost">Save AI Scoring</button></form><?php endif; ?></article><?php endforeach; ?>
  <h3>Create Quick Challenge instance</h3>
  <form action="admin-quick-challenge-action.php" method="post" class="form-card"><?php echo csrf_field(); ?><input type="hidden" name="action" value="create_instance">
    <label>Published template<select name="version_guid" required><option value="">Select</option><?php foreach($quickChallengeTemplates as$template): if($template['status']!=='Published')continue; ?><option value="<?php echo e((string)$template['version_guid']); ?>"><?php echo e((string)$template['display_name'].' · '.$template['difficulty']); ?></option><?php endforeach; ?></select></label>
    <label>Challenge title<input name="title" maxlength="180" required></label><label>Description<textarea name="description" maxlength="2000" required></textarea></label>
    <?php if(($admin['role']??'')===YUVA_ROLE_MASTER_ADMIN): ?><label>Mode<select name="experience_mode"><option value="quick_practice">Practice</option><option value="quick_ranked">Quick Ranked</option></select></label><label>Scope<select name="scope_type"><option value="practice">Platform practice</option><option value="organization">Organization</option></select></label><label>Organization code<input name="organization_code" maxlength="120"></label><?php else: ?><input type="hidden" name="experience_mode" value="quick_practice"><input type="hidden" name="scope_type" value="organization"><input type="hidden" name="organization_code" value="<?php echo e((string)$admin['organization_id']); ?>"><?php endif; ?>
    <label>Division<select name="division_code"><option value="junior">Junior (8–12)</option><option value="senior">Senior (13–17)</option><option value="young-adult">Young Adult / College (18–21)</option></select></label><div class="field-grid"><label>Opens at UTC<input type="datetime-local" name="open_at" required></label><label>Deadline UTC<input type="datetime-local" name="submission_deadline" required></label></div><button class="button primary">Create Draft Quick Challenge</button>
  </form>
  <h3>Recent AI practice evaluations</h3><div class="table-wrap"><table><thead><tr><th>Safe identity</th><th>Status</th><th>Practice score</th><th>Benchmark</th><th>Action</th></tr></thead><tbody><?php foreach($quickChallengeEvaluations as$evaluation): ?><tr><td><?php echo e((string)($evaluation['avatar_code']??'explorer_rocket')); ?> <?php echo e((string)($evaluation['public_handle']??$evaluation['yuva_id'])); ?></td><td><?php echo e((string)$evaluation['status']); ?></td><td><?php echo $evaluation['total_score']===null?'—':e((string)$evaluation['total_score']); ?></td><td><?php echo e((string)$evaluation['benchmark_label']); ?></td><td><?php if(($admin['role']??'')===YUVA_ROLE_MASTER_ADMIN&&in_array($evaluation['status'],['Failed','Stale'],true)): ?><form action="admin-quick-challenge-action.php" method="post"><?php echo csrf_field(); ?><input type="hidden" name="action" value="reprocess_ai_evaluation"><input type="hidden" name="evaluation_guid" value="<?php echo e((string)$evaluation['evaluation_guid']); ?>"><button class="button ghost">Reprocess</button></form><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
</section>
