<?php
declare(strict_types=1);

final class CompetitionFoundationService
{
    private const STATUSES = ['Draft','Scheduled','Open','SubmissionsClosed','Archived'];
    private const TRANSITIONS = [
        'Draft'=>['Scheduled'], 'Scheduled'=>['Open'], 'Open'=>['SubmissionsClosed'],
        'SubmissionsClosed'=>['Archived'], 'Archived'=>[],
    ];
    private const DIVISIONS = [
        'junior'=>['Junior',8,12], 'senior'=>['Senior',13,17],
        'young-adult'=>['Young Adult / College',18,21],
    ];

    public function __construct(private PDO $pdo) {}

    public function create(array $actor, array $input): array
    {
        $scope = strtolower(trim((string)($input['scope_type']??'')));
        $organization = $scope==='organization' ? strtoupper(trim((string)($input['organization_code']??''))) : null;
        $this->authorizeManager($actor,$scope,$organization);
        $title=trim((string)($input['title']??''));$description=trim((string)($input['description']??''));
        $open=$this->date((string)($input['open_at']??''));$deadline=$this->date((string)($input['submission_deadline']??''));
        if($title===''||$this->textLength($title)>180||$description===''||$this->textLength($description)>2000||$open >= $deadline) throw new InvalidArgumentException('Valid challenge details and dates are required.');
        if($organization!==null&&!preg_match('/^[A-Z0-9][A-Z0-9-]{2,119}$/',$organization))throw new InvalidArgumentException('A valid organization code is required.');
        $divisionCode=strtolower(trim((string)($input['division_code']??'')));if(!isset(self::DIVISIONS[$divisionCode]))throw new InvalidArgumentException('A supported division is required.');
        $criteria=$this->criteria((string)($input['criteria_json']??''));$maximum=(float)($input['maximum_score']??100);if($maximum<=0||$maximum>1000)throw new InvalidArgumentException('A valid rubric maximum is required.');
        return Database::transaction(function(PDO $pdo)use($actor,$scope,$organization,$title,$description,$open,$deadline,$divisionCode,$criteria,$maximum):array{
            db_acquire_application_lock($pdo,'competition-create:'.($organization??'platform'),5000);
            $userId=$this->adminUserId((string)($actor['email']??''));
            $division=$this->divisionVersion($divisionCode,$userId);
            $rubric=$this->rubricVersion($title,$criteria,$maximum,$userId);
            $stmt=$pdo->prepare("INSERT dbo.competitions(title,[description],scope_type,owner_organization_code,[status],open_at,submission_deadline,rubric_version_id,created_by,created_by_email) OUTPUT INSERTED.id,CONVERT(NVARCHAR(36),INSERTED.competition_guid) AS competition_guid,INSERTED.row_version VALUES(:title,:description,:scope,:organization,N'Draft',:open_at,:deadline,:rubric,:creator,:email)");
            $stmt->execute(['title'=>$title,'description'=>$description,'scope'=>$scope,'organization'=>$organization,'open_at'=>$open->format('Y-m-d H:i:s'),'deadline'=>$deadline->format('Y-m-d H:i:s'),'rubric'=>$rubric,'creator'=>$userId,'email'=>strtolower((string)$actor['email'])]);$created=$stmt->fetch();if(!is_array($created))throw new RuntimeException('Challenge was not created.');
            $link=$pdo->prepare('INSERT dbo.competition_divisions(competition_id,division_version_id) OUTPUT INSERTED.id VALUES(:competition,:division)');$link->execute(['competition'=>(int)$created['id'],'division'=>$division]);$competitionDivision=(int)$link->fetchColumn();
            $this->audit((int)$created['id'],null,null,'CompetitionCreated',$actor,$organization,true,['scope'=>$scope]);
            return ['id'=>(int)$created['id'],'competition_guid'=>(string)$created['competition_guid'],'competition_division_id'=>$competitionDivision,'row_version'=>normalize_sqlsrv_rowversion_token($created['row_version'])];
        },'SERIALIZABLE',true);
    }

    public function transition(array $actor,string $guid,string $target,string $rowVersion): void
    {
        if(!in_array($target,self::STATUSES,true))throw new InvalidArgumentException('Unsupported challenge state.');$version=normalize_sqlsrv_rowversion_token($rowVersion);
        Database::transaction(function(PDO $pdo)use($actor,$guid,$target,$version):void{
            $q=$pdo->prepare("SELECT TOP(1)id,scope_type,owner_organization_code,[status],open_at,submission_deadline FROM dbo.competitions WITH(UPDLOCK,HOLDLOCK) WHERE competition_guid=:guid");$q->execute(['guid'=>$guid]);$row=$q->fetch();if(!is_array($row))throw new RuntimeException('Challenge was not found.');
            $this->authorizeManager($actor,(string)$row['scope_type'],$row['owner_organization_code']!==null?(string)$row['owner_organization_code']:null);
            if(!in_array($target,self::TRANSITIONS[(string)$row['status']]??[],true))throw new RuntimeException('Challenge lifecycle transition was rejected.');
            $u=$pdo->prepare("UPDATE dbo.competitions SET [status]=:target,updated_at=SYSUTCDATETIME() WHERE id=:id AND row_version=CONVERT(BINARY(8),:version,2)");$u->bindValue(':target',$target,PDO::PARAM_STR);$u->bindValue(':id',(int)$row['id'],PDO::PARAM_INT);$u->bindValue(':version',$version,PDO::PARAM_STR);$u->execute();if($u->rowCount()!==1)throw new RuntimeException('Stale challenge update was rejected.');
            $this->audit((int)$row['id'],null,null,'CompetitionStatusChanged',$actor,$row['owner_organization_code']!==null?(string)$row['owner_organization_code']:null,true,['from'=>$row['status'],'to'=>$target]);
        },'SERIALIZABLE',true);
    }

    public function availableForStudent(string $yuvaId): array { return $this->studentRows($yuvaId,false); }
    public function entriesForStudent(string $yuvaId): array { return $this->studentRows($yuvaId,true); }
    public function managedBy(array $actor): array
    {
        $role=(string)($actor['role']??'');$organization=strtoupper(trim((string)($actor['organization_id']??'')));
        $sql="SELECT competition.id,competition.competition_guid,competition.title,competition.[description],competition.scope_type,competition.owner_organization_code,competition.[status],competition.open_at,competition.submission_deadline,competition.rubric_version_id,competition.created_by,competition.created_by_email,competition.created_at,competition.updated_at,CONVERT(VARCHAR(16),competition.row_version,2) AS row_version,division.id competition_division_id,version.display_name division_name,rubric.display_name rubric_name,rubric.maximum_score FROM dbo.competitions competition JOIN dbo.competition_divisions division ON division.competition_id=competition.id JOIN dbo.competition_division_versions version ON version.id=division.division_version_id JOIN dbo.competition_rubric_versions rubric ON rubric.id=competition.rubric_version_id";
        if($role==='OrganizationAdmin'){$sql.=" WHERE competition.scope_type=N'organization' AND competition.owner_organization_code=:organization";}
        elseif($role!=='MasterAdmin')throw new RuntimeException('Challenge manager authorization is required.');
        $sql.=' ORDER BY competition.created_at DESC';$stmt=$this->pdo->prepare($sql);$stmt->execute($role==='OrganizationAdmin'?['organization'=>$organization]:[]);$rows=$stmt->fetchAll()?:[];foreach($rows as &$row){$row['row_version']=normalize_sqlsrv_rowversion_token($row['row_version']??null);}unset($row);return$rows;
    }

    public function managedEntries(array $actor): array
    {
        $role=(string)($actor['role']??'');$organization=strtoupper(trim((string)($actor['organization_id']??'')));
        $sql="SELECT competition.competition_guid,competition.title,competition.owner_organization_code,entry.entry_guid,entry.yuva_id,entry.[status] entry_status,student.public_handle,student.avatar_code,division_version.display_name division_name,submission.submission_guid,submission.[status] submission_status,submission.locked_at FROM dbo.competition_entries entry JOIN dbo.competitions competition ON competition.id=entry.competition_id JOIN dbo.students student ON student.id=entry.student_id JOIN dbo.competition_divisions division ON division.id=entry.competition_division_id JOIN dbo.competition_division_versions division_version ON division_version.id=division.division_version_id LEFT JOIN dbo.competition_submissions submission ON submission.entry_id=entry.id";
        if($role==='OrganizationAdmin'){$sql.=" WHERE competition.scope_type=N'organization' AND competition.owner_organization_code=:organization";}
        elseif($role!=='MasterAdmin')throw new RuntimeException('Challenge manager authorization is required.');
        $sql.=' ORDER BY competition.created_at DESC,entry.entered_at';$stmt=$this->pdo->prepare($sql);$stmt->execute($role==='OrganizationAdmin'?['organization'=>$organization]:[]);return$stmt->fetchAll()?:[];
    }

    public function join(string $yuvaId,string $competitionGuid,int $competitionDivisionId): array
    {
        return Database::transaction(function(PDO $pdo)use($yuvaId,$competitionGuid,$competitionDivisionId):array{
            db_acquire_application_lock($pdo,'competition-entry:'.strtoupper($yuvaId).':'.$competitionGuid,5000);
            $student=$this->student($yuvaId);
            $q=$pdo->prepare("SELECT competition.id competition_id,competition.scope_type,competition.owner_organization_code,competition.[status],competition.open_at,competition.submission_deadline,division.id competition_division_id,version.id division_version_id,version.division_code,version.display_name,version.version_number,version.min_age,version.max_age,version.eligibility_rule_json FROM dbo.competitions competition JOIN dbo.competition_divisions division ON division.competition_id=competition.id JOIN dbo.competition_division_versions version ON version.id=division.division_version_id WHERE competition.competition_guid=:guid AND division.id=:division");$q->execute(['guid'=>$competitionGuid,'division'=>$competitionDivisionId]);$competition=$q->fetch();if(!is_array($competition))throw new RuntimeException('Challenge is unavailable.');
            $now=new DateTimeImmutable('now',new DateTimeZone('UTC'));if($competition['status']!=='Open'||$now<$this->date((string)$competition['open_at'])||$now>=$this->date((string)$competition['submission_deadline']))throw new RuntimeException('Challenge is not open for entries.');
            if($competition['scope_type']==='organization'&&!$this->activeMembership((int)$student['id'],(string)$competition['owner_organization_code']))throw new RuntimeException('Active same-organization membership is required.');
            $age=$this->ageAt((string)($student['date_of_birth']??''),$this->date((string)$competition['open_at']));if($age===null||$age<(int)$competition['min_age']||$age>(int)$competition['max_age'])throw new RuntimeException('Student is not eligible for this division.');
            $snapshot=json_encode(['division_code'=>$competition['division_code'],'division_version'=>(int)$competition['version_number'],'min_age'=>(int)$competition['min_age'],'max_age'=>(int)$competition['max_age'],'age_at_open'=>$age,'rule'=>json_decode((string)$competition['eligibility_rule_json'],true),'evaluated_at'=>$now->format(DATE_ATOM)],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);
            $existing=$pdo->prepare('SELECT TOP(1)id,CONVERT(NVARCHAR(36),entry_guid) entry_guid,[status] FROM dbo.competition_entries WITH(UPDLOCK,HOLDLOCK) WHERE competition_id=:competition AND competition_division_id=:division AND student_id=:student');$existing->execute(['competition'=>$competition['competition_id'],'division'=>$competitionDivisionId,'student'=>$student['id']]);$prior=$existing->fetch();if(is_array($prior))return['status'=>'already-entered','entry_guid'=>(string)$prior['entry_guid']];
            $insert=$pdo->prepare("INSERT dbo.competition_entries(competition_id,competition_division_id,student_id,yuva_id,eligibility_snapshot_json) OUTPUT INSERTED.id,CONVERT(NVARCHAR(36),INSERTED.entry_guid) AS entry_guid VALUES(:competition,:division,:student,:yuva_id,:snapshot)");$insert->execute(['competition'=>$competition['competition_id'],'division'=>$competitionDivisionId,'student'=>$student['id'],'yuva_id'=>strtoupper($yuvaId),'snapshot'=>$snapshot]);$created=$insert->fetch();if(!is_array($created))throw new RuntimeException('Challenge entry was not created.');$this->audit((int)$competition['competition_id'],(int)$created['id'],null,'EntryCreated',['role'=>'Student','email'=>null],(string)($competition['owner_organization_code']??''),true,[]);return['status'=>'entered','entry_guid'=>(string)$created['entry_guid']];
        },'SERIALIZABLE',true);
    }

    public function lockResearch(string $yuvaId,string $entryGuid,array $research): array
    {
        return Database::transaction(function(PDO $pdo)use($yuvaId,$entryGuid,$research):array{
            $student=$this->student($yuvaId);$q=$pdo->prepare("SELECT entry.id entry_id,entry.[status] entry_status,entry.competition_id,competition.[status] competition_status,competition.submission_deadline FROM dbo.competition_entries entry WITH(UPDLOCK,HOLDLOCK) JOIN dbo.competitions competition ON competition.id=entry.competition_id WHERE entry.entry_guid=:guid AND entry.student_id=:student");$q->execute(['guid'=>$entryGuid,'student'=>$student['id']]);$entry=$q->fetch();if(!is_array($entry))throw new RuntimeException('Challenge entry is unavailable.');
            if($entry['competition_status']!=='Open'||new DateTimeImmutable('now',new DateTimeZone('UTC'))>=$this->date((string)$entry['submission_deadline']))throw new RuntimeException('Competition submission deadline has passed.');
            foreach(['research_notes','sources_used','presentation_outline','prepared_questions']as$key){if(trim((string)($research[$key]??''))==='')throw new InvalidArgumentException('A complete research submission is required.');}
            $snapshot=['research_notes'=>(string)$research['research_notes'],'sources_used'=>(string)$research['sources_used'],'presentation_outline'=>(string)$research['presentation_outline'],'prepared_questions'=>(string)$research['prepared_questions'],'file'=>['original'=>(string)($research['file_original']??''),'reference'=>(string)($research['file_stored']??''),'sha256'=>(string)($research['file_sha256']??''),'mime'=>(string)($research['file_mime']??''),'size'=>(int)($research['file_size']??0)]];
            $canonical=json_encode($snapshot,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);$hash=hash('sha256',$canonical);$provenance=json_encode(['captured_from'=>'student_research_workspace','captured_at'=>gmdate(DATE_ATOM),'workspace_updated_at'=>$research['updated_at']??null],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);
            $existing=$pdo->prepare('SELECT TOP(1)CONVERT(NVARCHAR(36),submission_guid) submission_guid,source_revision_hash FROM dbo.competition_submissions WITH(UPDLOCK,HOLDLOCK) WHERE entry_id=:entry');$existing->execute(['entry'=>$entry['entry_id']]);$prior=$existing->fetch();if(is_array($prior))return['status'=>'already-locked','submission_guid'=>(string)$prior['submission_guid'],'source_revision_hash'=>(string)$prior['source_revision_hash']];
            $insert=$pdo->prepare("INSERT dbo.competition_submissions(entry_id,source_type,source_reference,source_revision_hash,source_snapshot_json,provenance_json) OUTPUT INSERTED.id,CONVERT(NVARCHAR(36),INSERTED.submission_guid) AS submission_guid VALUES(:entry,N'research_snapshot',:reference,:hash,:snapshot,:provenance)");$insert->execute(['entry'=>$entry['entry_id'],'reference'=>'research:'.strtoupper($yuvaId).':'.$hash,'hash'=>$hash,'snapshot'=>$canonical,'provenance'=>$provenance]);$created=$insert->fetch();if(!is_array($created))throw new RuntimeException('Competition submission was not locked.');$pdo->prepare("UPDATE dbo.competition_entries SET [status]=N'Submitted',updated_at=SYSUTCDATETIME() WHERE id=:id AND [status]=N'Entered'")->execute(['id'=>$entry['entry_id']]);$this->audit((int)$entry['competition_id'],(int)$entry['entry_id'],(int)$created['id'],'SubmissionLocked',['role'=>'Student','email'=>null],null,true,['source_type'=>'research_snapshot','source_revision_hash'=>$hash]);return['status'=>'locked','submission_guid'=>(string)$created['submission_guid'],'source_revision_hash'=>$hash];
        },'SERIALIZABLE',true);
    }

    private function studentRows(string $yuvaId,bool $onlyEntries):array{$student=$this->student($yuvaId);$sql="SELECT competition.competition_guid,competition.title,competition.[description],competition.scope_type,competition.owner_organization_code,competition.[status],competition.open_at,competition.submission_deadline,division.id competition_division_id,version.display_name division_name,version.min_age,version.max_age,rubric.display_name rubric_name,rubric.maximum_score,entry.entry_guid,entry.[status] entry_status,submission.submission_guid,submission.[status] submission_status,submission.locked_at FROM dbo.competitions competition JOIN dbo.competition_divisions division ON division.competition_id=competition.id JOIN dbo.competition_division_versions version ON version.id=division.division_version_id JOIN dbo.competition_rubric_versions rubric ON rubric.id=competition.rubric_version_id LEFT JOIN dbo.competition_entries entry ON entry.competition_id=competition.id AND entry.competition_division_id=division.id AND entry.student_id=:student LEFT JOIN dbo.competition_submissions submission ON submission.entry_id=entry.id WHERE ";$sql.=$onlyEntries?'entry.id IS NOT NULL':"competition.[status] IN(N'Scheduled',N'Open') AND (competition.scope_type=N'practice' OR EXISTS(SELECT 1 FROM dbo.organization_student_membership_requests membership WHERE membership.student_id=:member AND membership.organization_code=competition.owner_organization_code AND membership.[status]=N'Active'))";$sql.=' ORDER BY competition.open_at,competition.id';$stmt=$this->pdo->prepare($sql);$params=['student'=>$student['id']];if(!$onlyEntries)$params['member']=$student['id'];$stmt->execute($params);$rows=$stmt->fetchAll()?:[];if($onlyEntries)return$rows;return array_values(array_filter($rows,function(array$row)use($student):bool{$age=$this->ageAt((string)($student['date_of_birth']??''),$this->date((string)$row['open_at']));return$age!==null&&$age>=(int)$row['min_age']&&$age<=(int)$row['max_age'];}));}
    private function student(string $yuvaId):array{$stmt=$this->pdo->prepare("SELECT TOP(1)id,yuva_id,date_of_birth FROM dbo.students WHERE yuva_id=:yuva_id AND approval_status=N'approved'");$stmt->execute(['yuva_id'=>strtoupper(trim($yuvaId))]);$row=$stmt->fetch();if(!is_array($row))throw new RuntimeException('Approved student is required.');return$row;}
    private function authorizeManager(array $actor,string $scope,?string $organization):void{$role=(string)($actor['role']??'');if($role==='MasterAdmin')return;if($role!=='OrganizationAdmin'||$scope!=='organization'||$organization===null||!hash_equals(strtoupper((string)($actor['organization_id']??'')),strtoupper($organization)))throw new RuntimeException('Challenge manager scope was rejected.');}
    private function activeMembership(int $student,string $organization):bool{$stmt=$this->pdo->prepare("SELECT TOP(1)1 FROM dbo.organization_student_membership_requests WHERE student_id=:student AND organization_code=:organization AND [status]=N'Active'");$stmt->execute(['student'=>$student,'organization'=>$organization]);return$stmt->fetchColumn()!==false;}
    private function adminUserId(string $email):?int{$stmt=$this->pdo->prepare("SELECT TOP(1)id FROM dbo.users WHERE LOWER(email)=:email AND role=N'admin' AND [status]=N'active'");$stmt->execute(['email'=>strtolower(trim($email))]);$id=$stmt->fetchColumn();return$id===false?null:(int)$id;}
    private function divisionVersion(string $code,?int $creator):int{[$name,$min,$max]=self::DIVISIONS[$code];$rule=json_encode(['type'=>'age_at_competition_open','min_age'=>$min,'max_age'=>$max,'version'=>1],JSON_THROW_ON_ERROR);$find=$this->pdo->prepare('SELECT TOP(1)id FROM dbo.competition_division_versions WHERE division_code=:code AND eligibility_rule_json=:rule ORDER BY version_number DESC');$find->execute(['code'=>$code,'rule'=>$rule]);$id=$find->fetchColumn();if($id!==false)return(int)$id;$next=$this->pdo->prepare('SELECT ISNULL(MAX(version_number),0)+1 FROM dbo.competition_division_versions WITH(UPDLOCK,HOLDLOCK) WHERE division_code=:code');$next->execute(['code'=>$code]);$version=(int)$next->fetchColumn();$insert=$this->pdo->prepare('INSERT dbo.competition_division_versions(division_code,display_name,version_number,min_age,max_age,eligibility_rule_json,created_by) OUTPUT INSERTED.id VALUES(:code,:name,:version,:min,:max,:rule,:creator)');$insert->execute(compact('code','name','version','min','max','rule','creator'));return(int)$insert->fetchColumn();}
    private function rubricVersion(string $title,string $criteria,float $maximum,?int $creator):int{$code='challenge-'.substr(hash('sha256',strtolower($title)),0,16);$next=$this->pdo->prepare('SELECT ISNULL(MAX(version_number),0)+1 FROM dbo.competition_rubric_versions WITH(UPDLOCK,HOLDLOCK) WHERE rubric_code=:code');$next->execute(['code'=>$code]);$version=(int)$next->fetchColumn();$insert=$this->pdo->prepare('INSERT dbo.competition_rubric_versions(rubric_code,display_name,version_number,criteria_json,maximum_score,created_by) OUTPUT INSERTED.id VALUES(:code,:name,:version,:criteria,:maximum,:creator)');$insert->execute(['code'=>$code,'name'=>$title.' Rubric','version'=>$version,'criteria'=>$criteria,'maximum'=>$maximum,'creator'=>$creator]);return(int)$insert->fetchColumn();}
    private function criteria(string $json):string{$decoded=json_decode($json,true);if(!is_array($decoded)||$decoded===[])throw new InvalidArgumentException('A valid rubric is required.');$weight=0;foreach($decoded as$item){if(!is_array($item)||trim((string)($item['name']??''))===''||!is_numeric($item['weight']??null))throw new InvalidArgumentException('A valid rubric is required.');$weight+=(float)$item['weight'];}if(abs($weight-100)>0.001)throw new InvalidArgumentException('Rubric weights must total 100.');return json_encode($decoded,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);}
    private function ageAt(string $dob,DateTimeImmutable $at):?int{if(trim($dob)==='')return null;try{$birth=new DateTimeImmutable($dob,new DateTimeZone('UTC'));}catch(Throwable){return null;}if($birth>$at)return null;return(int)$birth->diff($at)->y;}
    private function date(string $value):DateTimeImmutable{try{$date=new DateTimeImmutable($value,new DateTimeZone('UTC'));}catch(Throwable){throw new InvalidArgumentException('A valid UTC date is required.');}return$date->setTimezone(new DateTimeZone('UTC'));}
    private function textLength(string $value):int{return function_exists('mb_strlen')?mb_strlen($value,'UTF-8'):strlen($value);}
    private function audit(?int $competition,?int $entry,?int $submission,string $action,array $actor,?string $organization,bool $success,array $metadata):void{$stmt=$this->pdo->prepare('INSERT dbo.competition_audit(competition_id,entry_id,submission_id,action_type,actor_type,actor_identifier,organization_code,succeeded,metadata_json) VALUES(:competition,:entry,:submission,:action,:type,:identifier,:organization,:succeeded,:metadata)');$stmt->execute(['competition'=>$competition,'entry'=>$entry,'submission'=>$submission,'action'=>$action,'type'=>(string)($actor['role']??'System'),'identifier'=>$actor['email']??null,'organization'=>$organization,'succeeded'=>$success?1:0,'metadata'=>$metadata===[]?null:json_encode($metadata,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES)]);}
}
