<?php
declare(strict_types=1);

final class QuickChallengeService
{
    private const TYPES=['speech','persuasion','impromptu','explain','storytelling','elevator_pitch','critical_thinking','teaching','research_summary','leadership_reflection'];
    private const DIFFICULTIES=['Beginner','Intermediate','Advanced'];
    private const SKILLS=['public-speaking','storytelling','persuasion','research','critical-thinking','impromptu-speaking','presentation-delivery','communication-clarity','leadership','teaching'];
    private const DIVISIONS=['junior'=>['Junior',8,12],'senior'=>['Senior',13,17],'young-adult'=>['Young Adult / College',18,21]];
    public function __construct(private PDO $pdo) {}

    public function createTemplate(array $actor,array $input):array
    {
        $this->master($actor);
        $code=strtolower(trim((string)($input['template_code']??'')));$name=trim((string)($input['display_name']??''));$type=strtolower(trim((string)($input['challenge_type']??'')));
        $prompt=trim((string)($input['prompt_text']??''));$instructions=trim((string)($input['instructions']??''));$difficulty=(string)($input['difficulty']??'');
        $preparation=(int)($input['preparation_seconds']??0);$response=(int)($input['response_seconds']??0);$attempts=(int)($input['maximum_attempts']??0);
        $policy=(string)($input['attempt_policy']??'best');$reveal=(string)($input['prompt_reveal_mode']??'visible');$skills=array_values(array_unique(array_map('strval',(array)($input['skills']??[]))));
        if(!preg_match('/^[a-z0-9][a-z0-9-]{2,79}$/',$code)||$name===''||$this->length($name)>160||!in_array($type,self::TYPES,true)||$prompt===''||$this->length($prompt)>2000||$instructions===''||$this->length($instructions)>2000)throw new InvalidArgumentException('Valid template details are required.');
        if(!in_array($difficulty,self::DIFFICULTIES,true)||$preparation<0||$preparation>600||$response<15||$response>900||$attempts<1||$attempts>20||!in_array($policy,['best','latest'],true)||!in_array($reveal,['visible','on_start'],true))throw new InvalidArgumentException('Valid difficulty, timing, and attempt rules are required.');
        if($skills===[]||array_diff($skills,self::SKILLS)!==[])throw new InvalidArgumentException('At least one supported skill is required.');
        return Database::transaction(function(PDO $pdo)use($actor,$code,$name,$type,$prompt,$instructions,$difficulty,$preparation,$response,$attempts,$policy,$reveal,$skills):array{
            db_acquire_application_lock($pdo,'quick-template:'.$code,5000);$user=$this->adminUser((string)$actor['email']);
            $insert=$pdo->prepare("INSERT dbo.quick_challenge_templates(template_code,display_name,challenge_type,created_by,created_by_email) OUTPUT INSERTED.id,CONVERT(NVARCHAR(36),INSERTED.template_guid) AS template_guid VALUES(:code,:name,:type,:creator,:email)");
            $insert->execute(['code'=>$code,'name'=>$name,'type'=>$type,'creator'=>$user,'email'=>strtolower((string)$actor['email'])]);$template=$insert->fetch();if(!is_array($template))throw new RuntimeException('Quick Challenge template was not created.');
            $rubric=$this->rubric($code,$name,$user);$version=$pdo->prepare("INSERT dbo.quick_challenge_template_versions(template_id,version_number,prompt_text,instructions,difficulty,preparation_seconds,response_seconds,maximum_attempts,attempt_policy,prompt_reveal_mode,rubric_version_id,created_by) OUTPUT INSERTED.id,CONVERT(NVARCHAR(36),INSERTED.version_guid) AS version_guid VALUES(:template,1,:prompt,:instructions,:difficulty,:preparation,:response,:attempts,:policy,:reveal,:rubric,:creator)");
            $version->execute(['template'=>$template['id'],'prompt'=>$prompt,'instructions'=>$instructions,'difficulty'=>$difficulty,'preparation'=>$preparation,'response'=>$response,'attempts'=>$attempts,'policy'=>$policy,'reveal'=>$reveal,'rubric'=>$rubric,'creator'=>$user]);$created=$version->fetch();if(!is_array($created))throw new RuntimeException('Quick Challenge template version was not created.');
            $skill=$pdo->prepare('INSERT dbo.quick_challenge_template_version_skills(template_version_id,skill_id,is_primary) SELECT :version,id,:primary FROM dbo.quick_challenge_skills WHERE skill_code=:skill AND is_active=1');foreach($skills as$i=>$codeValue){$skill->execute(['version'=>$created['id'],'primary'=>$i===0?1:0,'skill'=>$codeValue]);if($skill->rowCount()!==1)throw new RuntimeException('Quick Challenge skill was not linked.');}
            return ['template_guid'=>(string)$template['template_guid'],'version_guid'=>(string)$created['version_guid']];
        },'SERIALIZABLE',true);
    }

    public function publishTemplate(array $actor,string $guid,string $rowVersion):void
    {
        $this->master($actor);$version=normalize_sqlsrv_rowversion_token($rowVersion);
        $stmt=$this->pdo->prepare("UPDATE dbo.quick_challenge_templates SET [status]=N'Published',updated_at=SYSUTCDATETIME() WHERE template_guid=:guid AND [status]=N'Draft' AND row_version=CONVERT(BINARY(8),:version,2)");$stmt->bindValue(':guid',$guid,PDO::PARAM_STR);$stmt->bindValue(':version',$version,PDO::PARAM_STR);$stmt->execute();if($stmt->rowCount()!==1)throw new RuntimeException('Template publish was rejected or stale.');
    }

    public function templates(array $actor):array
    {
        $role=(string)($actor['role']??'');if(!in_array($role,['MasterAdmin','OrganizationAdmin'],true))throw new RuntimeException('Challenge manager authorization is required.');
        $where=$role==='MasterAdmin'?'':" WHERE template.[status]=N'Published'";
        $sql="SELECT template.template_guid,template.template_code,template.display_name,template.challenge_type,template.[status],template.row_version AS row_version_binary,version.id template_version_id,version.version_guid,version.version_number,version.prompt_text,version.instructions,version.difficulty,version.preparation_seconds,version.response_seconds,version.maximum_attempts,version.attempt_policy,version.prompt_reveal_mode,STRING_AGG(skill.display_name,N', ') WITHIN GROUP(ORDER BY link.is_primary DESC,skill.display_name) skills FROM dbo.quick_challenge_templates template JOIN dbo.quick_challenge_template_versions version ON version.template_id=template.id JOIN dbo.quick_challenge_template_version_skills link ON link.template_version_id=version.id JOIN dbo.quick_challenge_skills skill ON skill.id=link.skill_id".$where." GROUP BY template.template_guid,template.template_code,template.display_name,template.challenge_type,template.[status],template.row_version,version.id,version.version_guid,version.version_number,version.prompt_text,version.instructions,version.difficulty,version.preparation_seconds,version.response_seconds,version.maximum_attempts,version.attempt_policy,version.prompt_reveal_mode ORDER BY template.created_at DESC";
        $rows=$this->pdo->query($sql)->fetchAll()?:[];foreach($rows as&$row){$row['row_version']=normalize_sqlsrv_rowversion_token($row['row_version_binary']??null);unset($row['row_version_binary']);}unset($row);return$rows;
    }

    public function createInstance(array $actor,array $input):array
    {
        $scope=(string)($input['scope_type']??'practice');$organization=$scope==='organization'?strtoupper(trim((string)($input['organization_code']??''))):null;$this->manager($actor,$scope,$organization);
        if(!in_array($scope,['practice','organization'],true)||($organization!==null&&!preg_match('/^[A-Z0-9][A-Z0-9-]{2,119}$/',$organization)))throw new InvalidArgumentException('Valid challenge scope is required.');
        $versionGuid=trim((string)($input['version_guid']??''));$title=trim((string)($input['title']??''));$description=trim((string)($input['description']??''));$divisionCode=(string)($input['division_code']??'');$mode=(string)($input['experience_mode']??'quick_practice');
        $open=$this->date((string)($input['open_at']??''));$deadline=$this->date((string)($input['submission_deadline']??''));if($title===''||$description===''||$open>=$deadline||!isset(self::DIVISIONS[$divisionCode])||!in_array($mode,['quick_practice','quick_ranked'],true))throw new InvalidArgumentException('Valid Quick Challenge instance details are required.');
        return Database::transaction(function(PDO $pdo)use($actor,$scope,$organization,$versionGuid,$title,$description,$divisionCode,$mode,$open,$deadline):array{
            db_acquire_application_lock($pdo,'quick-instance:'.($organization??'platform').':'.$versionGuid,5000);$user=$this->adminUser((string)$actor['email']);
            $find=$pdo->prepare("SELECT TOP(1)version.id,version.rubric_version_id FROM dbo.quick_challenge_template_versions version JOIN dbo.quick_challenge_templates template ON template.id=version.template_id WHERE version.version_guid=:guid AND template.[status]=N'Published' AND version.is_frozen=1");$find->execute(['guid'=>$versionGuid]);$template=$find->fetch();if(!is_array($template))throw new RuntimeException('Published frozen template version is required.');
            $division=$this->division($divisionCode,$user);$insert=$pdo->prepare("INSERT dbo.competitions(title,[description],scope_type,owner_organization_code,[status],open_at,submission_deadline,rubric_version_id,created_by,created_by_email,quick_template_version_id,experience_mode) OUTPUT INSERTED.id,CONVERT(NVARCHAR(36),INSERTED.competition_guid) AS competition_guid,INSERTED.row_version VALUES(:title,:description,:scope,:organization,N'Draft',:open_at,:deadline,:rubric,:creator,:email,:template,:mode)");
            $insert->execute(['title'=>$title,'description'=>$description,'scope'=>$scope,'organization'=>$organization,'open_at'=>$open->format('Y-m-d H:i:s'),'deadline'=>$deadline->format('Y-m-d H:i:s'),'rubric'=>$template['rubric_version_id'],'creator'=>$user,'email'=>strtolower((string)$actor['email']),'template'=>$template['id'],'mode'=>$mode]);$created=$insert->fetch();if(!is_array($created))throw new RuntimeException('Quick Challenge instance was not created.');
            $link=$pdo->prepare('INSERT dbo.competition_divisions(competition_id,division_version_id) OUTPUT INSERTED.id VALUES(:competition,:division)');$link->execute(['competition'=>$created['id'],'division'=>$division]);$divisionId=(int)$link->fetchColumn();
            return ['competition_guid'=>(string)$created['competition_guid'],'competition_division_id'=>$divisionId,'row_version'=>normalize_sqlsrv_rowversion_token($created['row_version'])];
        },'SERIALIZABLE',true);
    }

    public function studentChallenges(string $yuvaId):array
    {
        $student=$this->student($yuvaId);$sql="SELECT competition.competition_guid,competition.title,competition.[description],competition.scope_type,competition.owner_organization_code,competition.[status],competition.open_at,competition.submission_deadline,competition.experience_mode,division.id competition_division_id,division_version.display_name division_name,version.version_guid,version.prompt_text,version.instructions,version.difficulty,version.preparation_seconds,version.response_seconds,version.maximum_attempts,version.prompt_reveal_mode,template.id template_id,template.display_name template_name,entry.entry_guid,entry.[status] entry_status,(SELECT COUNT(*) FROM dbo.quick_challenge_attempts a WHERE a.competition_entry_id=entry.id) attempt_count,best.best_score,best.score_version FROM dbo.competitions competition JOIN dbo.quick_challenge_template_versions version ON version.id=competition.quick_template_version_id JOIN dbo.quick_challenge_templates template ON template.id=version.template_id JOIN dbo.competition_divisions division ON division.competition_id=competition.id JOIN dbo.competition_division_versions division_version ON division_version.id=division.division_version_id LEFT JOIN dbo.competition_entries entry ON entry.competition_id=competition.id AND entry.competition_division_id=division.id AND entry.student_id=:student LEFT JOIN dbo.student_challenge_personal_bests best ON best.student_id=:best_student AND best.template_id=template.id WHERE competition.experience_mode IN(N'quick_practice',N'quick_ranked') AND competition.[status] IN(N'Scheduled',N'Open') AND (competition.scope_type=N'practice' OR EXISTS(SELECT 1 FROM dbo.organization_student_membership_requests membership WHERE membership.student_id=:member AND membership.organization_code=competition.owner_organization_code AND membership.[status]=N'Active')) ORDER BY competition.open_at,competition.id";$stmt=$this->pdo->prepare($sql);$stmt->execute(['student'=>$student['id'],'best_student'=>$student['id'],'member'=>$student['id']]);$rows=$stmt->fetchAll()?:[];foreach($rows as&$row){if($row['prompt_reveal_mode']==='on_start')$row['prompt_text']='Prompt revealed when you start.';}unset($row);return$rows;
    }

    public function startAttempt(string $yuvaId,string $competitionGuid,int $divisionId):array
    {
        return Database::transaction(function(PDO $pdo)use($yuvaId,$competitionGuid,$divisionId):array{
            $student=$this->student($yuvaId);db_acquire_application_lock($pdo,'quick-attempt:'.$student['id'].':'.$competitionGuid,5000);
            $q=$pdo->prepare("SELECT competition.id competition_id,competition.[status],competition.open_at,competition.submission_deadline,competition.scope_type,competition.owner_organization_code,division.id competition_division_id,division_version.division_code,division_version.version_number division_version_number,division_version.min_age,division_version.max_age,division_version.eligibility_rule_json,version.id version_id,version.prompt_text,version.preparation_seconds,version.response_seconds,version.maximum_attempts,version.prompt_reveal_mode FROM dbo.competitions competition JOIN dbo.competition_divisions division ON division.competition_id=competition.id JOIN dbo.competition_division_versions division_version ON division_version.id=division.division_version_id JOIN dbo.quick_challenge_template_versions version ON version.id=competition.quick_template_version_id WHERE competition.competition_guid=:competition AND division.id=:division AND competition.experience_mode IN(N'quick_practice',N'quick_ranked')");$q->execute(['competition'=>$competitionGuid,'division'=>$divisionId]);$row=$q->fetch();if(!is_array($row))throw new RuntimeException('Quick Challenge is unavailable.');
            $now=new DateTimeImmutable('now',new DateTimeZone('UTC'));if($row['status']!=='Open'||$now<$this->date((string)$row['open_at'])||$now>=$this->date((string)$row['submission_deadline']))throw new RuntimeException('Quick Challenge is not open.');if($row['scope_type']==='organization'&&!$this->activeMembership((int)$student['id'],(string)$row['owner_organization_code']))throw new RuntimeException('Active same-organization membership is required.');
            $age=$this->ageAt((string)$student['date_of_birth'],$this->date((string)$row['open_at']));if($age===null||$age<(int)$row['min_age']||$age>(int)$row['max_age'])throw new RuntimeException('Student is not eligible for this division.');
            $entryQuery=$pdo->prepare('SELECT TOP(1)id,[status] FROM dbo.competition_entries WITH(UPDLOCK,HOLDLOCK) WHERE competition_id=:competition AND competition_division_id=:division AND student_id=:student');$entryQuery->execute(['competition'=>$row['competition_id'],'division'=>$divisionId,'student'=>$student['id']]);$entry=$entryQuery->fetch();
            if(!is_array($entry)){$snapshot=json_encode(['division_code'=>$row['division_code'],'division_version'=>(int)$row['division_version_number'],'min_age'=>(int)$row['min_age'],'max_age'=>(int)$row['max_age'],'age_at_open'=>$age,'rule'=>json_decode((string)$row['eligibility_rule_json'],true),'evaluated_at'=>$now->format(DATE_ATOM)],JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES);$insertEntry=$pdo->prepare('INSERT dbo.competition_entries(competition_id,competition_division_id,student_id,yuva_id,eligibility_snapshot_json) OUTPUT INSERTED.id VALUES(:competition,:division,:student,:yuva_id,:snapshot)');$insertEntry->execute(['competition'=>$row['competition_id'],'division'=>$divisionId,'student'=>$student['id'],'yuva_id'=>strtoupper($yuvaId),'snapshot'=>$snapshot]);$entry=['id'=>(int)$insertEntry->fetchColumn(),'status'=>'Entered'];$this->audit((int)$row['competition_id'],(int)$entry['id'],'EntryCreated',['yuva_id'=>strtoupper($yuvaId)]);}
            if(($entry['status']??'')==='Withdrawn')throw new RuntimeException('Quick Challenge entry is unavailable.');$row['entry_id']=(int)$entry['id'];
            $count=$pdo->prepare('SELECT COUNT(*) FROM dbo.quick_challenge_attempts WITH(UPDLOCK,HOLDLOCK) WHERE competition_entry_id=:entry');$count->execute(['entry'=>$row['entry_id']]);$number=(int)$count->fetchColumn()+1;if($number>(int)$row['maximum_attempts'])throw new RuntimeException('Attempt limit reached.');
            $started=$now->modify('+'.(int)$row['preparation_seconds'].' seconds');$responseDeadline=$started->modify('+'.(int)$row['response_seconds'].' seconds');if($responseDeadline>$this->date((string)$row['submission_deadline']))$responseDeadline=$this->date((string)$row['submission_deadline']);
            $insert=$pdo->prepare("INSERT dbo.quick_challenge_attempts(competition_entry_id,student_id,template_version_id,attempt_number,prompt_revealed_at,started_at,response_deadline_at) OUTPUT INSERTED.id,CONVERT(NVARCHAR(36),INSERTED.attempt_guid) AS attempt_guid,INSERTED.row_version VALUES(:entry,:student,:version,:number,:revealed,:started,:deadline)");$insert->execute(['entry'=>$row['entry_id'],'student'=>$student['id'],'version'=>$row['version_id'],'number'=>$number,'revealed'=>$now->format('Y-m-d H:i:s'),'started'=>$started->format('Y-m-d H:i:s'),'deadline'=>$responseDeadline->format('Y-m-d H:i:s')]);$created=$insert->fetch();if(!is_array($created))throw new RuntimeException('Quick Challenge attempt was not started.');$this->audit((int)$row['competition_id'],(int)$row['entry_id'],'QuickAttemptStarted',['attempt_guid'=>$created['attempt_guid'],'attempt_number'=>$number]);
            return ['attempt_guid'=>(string)$created['attempt_guid'],'attempt_number'=>$number,'prompt'=>(string)$row['prompt_text'],'prompt_reveal_mode'=>(string)$row['prompt_reveal_mode'],'started_at'=>$started->format(DATE_ATOM),'response_deadline_at'=>$responseDeadline->format(DATE_ATOM),'row_version'=>normalize_sqlsrv_rowversion_token($created['row_version'])];
        },'SERIALIZABLE',true);
    }

    public function submitAttempt(string $yuvaId,string $attemptGuid,string $rowVersion,string $responseText):array
    {
        $version=normalize_sqlsrv_rowversion_token($rowVersion);$responseText=trim($responseText);if($responseText===''||$this->length($responseText)>12000)throw new InvalidArgumentException('A valid challenge response is required.');
        return Database::transaction(function(PDO $pdo)use($yuvaId,$attemptGuid,$version,$responseText):array{
            $student=$this->student($yuvaId);$q=$pdo->prepare("SELECT attempt.id,attempt.response_deadline_at,attempt.started_at,attempt.[status],entry.id entry_id,competition.id competition_id,competition.submission_deadline FROM dbo.quick_challenge_attempts attempt WITH(UPDLOCK,HOLDLOCK) JOIN dbo.competition_entries entry ON entry.id=attempt.competition_entry_id JOIN dbo.competitions competition ON competition.id=entry.competition_id WHERE attempt.attempt_guid=:guid AND attempt.student_id=:student AND entry.student_id=:student_owner");$q->execute(['guid'=>$attemptGuid,'student'=>$student['id'],'student_owner'=>$student['id']]);$attempt=$q->fetch();if(!is_array($attempt))throw new RuntimeException('Quick Challenge attempt is unavailable.');$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));if($attempt['status']!=='Started'||$now<$this->date((string)$attempt['started_at'])||$now>$this->date((string)$attempt['response_deadline_at'])||$now>$this->date((string)$attempt['submission_deadline']))throw new RuntimeException('Quick Challenge timing window has closed.');
            $snapshot=json_encode(['response_text'=>$responseText],JSON_THROW_ON_ERROR|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$hash=hash('sha256',$snapshot);$u=$pdo->prepare("UPDATE dbo.quick_challenge_attempts SET [status]=N'Submitted',submitted_at=SYSUTCDATETIME(),source_type=N'text_response',source_reference=:reference,source_revision_hash=:hash,source_snapshot_json=:snapshot WHERE id=:id AND [status]=N'Started' AND row_version=CONVERT(BINARY(8),:version,2)");$u->bindValue(':reference','quick-response:'.$attemptGuid.':'.$hash,PDO::PARAM_STR);$u->bindValue(':hash',$hash,PDO::PARAM_STR);$u->bindValue(':snapshot',$snapshot,PDO::PARAM_STR);$u->bindValue(':id',(int)$attempt['id'],PDO::PARAM_INT);$u->bindValue(':version',$version,PDO::PARAM_STR);$u->execute();if($u->rowCount()!==1)throw new RuntimeException('Stale or duplicate attempt submission was rejected.');$this->audit((int)$attempt['competition_id'],(int)$attempt['entry_id'],'QuickAttemptSubmitted',['attempt_guid'=>$attemptGuid,'source_revision_hash'=>$hash]);return['status'=>'submitted','source_revision_hash'=>$hash];
        },'SERIALIZABLE',true);
    }

    public function recordPracticeScore(array $actor,string $attemptGuid,float $score,string $scoreVersion,string $source):array
    {
        $this->master($actor);if($score<0||$score>100||!preg_match('/^[A-Za-z0-9][A-Za-z0-9._-]{2,79}$/',$scoreVersion)||!in_array($source,['AIPractice','HumanPractice'],true))throw new InvalidArgumentException('Valid versioned practice score is required.');
        return Database::transaction(function(PDO $pdo)use($attemptGuid,$score,$scoreVersion,$source):array{
            $q=$pdo->prepare("SELECT attempt.id,attempt.student_id,attempt.practice_score,attempt.score_version,version.template_id FROM dbo.quick_challenge_attempts attempt WITH(UPDLOCK,HOLDLOCK) JOIN dbo.quick_challenge_template_versions version ON version.id=attempt.template_version_id WHERE attempt.attempt_guid=:guid AND attempt.[status]=N'Submitted'");$q->execute(['guid'=>$attemptGuid]);$attempt=$q->fetch();if(!is_array($attempt))throw new RuntimeException('Submitted attempt is required.');if($attempt['practice_score']!==null)return['status'=>'already-scored','new_personal_best'=>false];
            $pdo->prepare('UPDATE dbo.quick_challenge_attempts SET practice_score=:score,score_version=:version,score_source=:source WHERE id=:id AND practice_score IS NULL')->execute(['score'=>$score,'version'=>$scoreVersion,'source'=>$source,'id'=>$attempt['id']]);
            $best=$pdo->prepare('SELECT TOP(1)id,best_score FROM dbo.student_challenge_personal_bests WITH(UPDLOCK,HOLDLOCK) WHERE student_id=:student AND template_id=:template AND score_version=:version');$best->execute(['student'=>$attempt['student_id'],'template'=>$attempt['template_id'],'version'=>$scoreVersion]);$prior=$best->fetch();$isBest=!is_array($prior)||$score>(float)$prior['best_score'];if(!is_array($prior)){$pdo->prepare('INSERT dbo.student_challenge_personal_bests(student_id,template_id,score_version,best_attempt_id,best_score,achieved_at) VALUES(:student,:template,:version,:attempt,:score,SYSUTCDATETIME())')->execute(['student'=>$attempt['student_id'],'template'=>$attempt['template_id'],'version'=>$scoreVersion,'attempt'=>$attempt['id'],'score'=>$score]);}elseif($isBest){$pdo->prepare('UPDATE dbo.student_challenge_personal_bests SET best_attempt_id=:attempt,best_score=:score,achieved_at=SYSUTCDATETIME(),updated_at=SYSUTCDATETIME() WHERE id=:id')->execute(['attempt'=>$attempt['id'],'score'=>$score,'id'=>$prior['id']]);}return['status'=>'scored','new_personal_best'=>$isBest,'previous_best'=>is_array($prior)?(float)$prior['best_score']:null,'score'=>$score];
        },'SERIALIZABLE',true);
    }

    private function master(array $actor):void{if(($actor['role']??'')!=='MasterAdmin')throw new RuntimeException('Master Admin authorization is required.');}
    private function manager(array $actor,string $scope,?string $organization):void{if(($actor['role']??'')==='MasterAdmin')return;if(($actor['role']??'')!=='OrganizationAdmin'||$scope!=='organization'||$organization===null||!hash_equals(strtoupper((string)($actor['organization_id']??'')),$organization))throw new RuntimeException('Challenge manager scope was rejected.');}
    private function student(string $yuvaId):array{$stmt=$this->pdo->prepare("SELECT TOP(1)id,yuva_id,date_of_birth FROM dbo.students WHERE yuva_id=:yuva_id AND approval_status=N'approved'");$stmt->execute(['yuva_id'=>strtoupper(trim($yuvaId))]);$row=$stmt->fetch();if(!is_array($row))throw new RuntimeException('Approved student is required.');return$row;}
    private function activeMembership(int $student,string $organization):bool{$stmt=$this->pdo->prepare("SELECT TOP(1)1 FROM dbo.organization_student_membership_requests WHERE student_id=:student AND organization_code=:organization AND [status]=N'Active'");$stmt->execute(compact('student','organization'));return$stmt->fetchColumn()!==false;}
    private function adminUser(string $email):?int{$stmt=$this->pdo->prepare("SELECT TOP(1)id FROM dbo.users WHERE LOWER(email)=:email AND role=N'admin' AND [status]=N'active'");$stmt->execute(['email'=>strtolower(trim($email))]);$id=$stmt->fetchColumn();return$id===false?null:(int)$id;}
    private function rubric(string $code,string $name,?int $creator):int{$criteria=json_encode([['name'=>'Content','weight'=>35],['name'=>'Structure','weight'=>25],['name'=>'Clarity','weight'=>25],['name'=>'Time discipline','weight'=>15]],JSON_THROW_ON_ERROR);$insert=$this->pdo->prepare("INSERT dbo.competition_rubric_versions(rubric_code,display_name,version_number,criteria_json,maximum_score,created_by) OUTPUT INSERTED.id VALUES(:code,:name,1,:criteria,100,:creator)");$insert->execute(['code'=>'quick-'.$code,'name'=>$name.' Practice Rubric','criteria'=>$criteria,'creator'=>$creator]);return(int)$insert->fetchColumn();}
    private function division(string $code,?int $creator):int{[$name,$min,$max]=self::DIVISIONS[$code];$rule=json_encode(['type'=>'age_at_competition_open','min_age'=>$min,'max_age'=>$max,'version'=>1],JSON_THROW_ON_ERROR);$find=$this->pdo->prepare('SELECT TOP(1)id FROM dbo.competition_division_versions WHERE division_code=:code AND eligibility_rule_json=:rule ORDER BY version_number DESC');$find->execute(['code'=>$code,'rule'=>$rule]);$id=$find->fetchColumn();if($id!==false)return(int)$id;$next=$this->pdo->prepare('SELECT ISNULL(MAX(version_number),0)+1 FROM dbo.competition_division_versions WITH(UPDLOCK,HOLDLOCK) WHERE division_code=:code');$next->execute(['code'=>$code]);$version=(int)$next->fetchColumn();$insert=$this->pdo->prepare('INSERT dbo.competition_division_versions(division_code,display_name,version_number,min_age,max_age,eligibility_rule_json,created_by) OUTPUT INSERTED.id VALUES(:code,:name,:version,:min,:max,:rule,:creator)');$insert->execute(compact('code','name','version','min','max','rule','creator'));return(int)$insert->fetchColumn();}
    private function date(string $value):DateTimeImmutable{try{return(new DateTimeImmutable($value,new DateTimeZone('UTC')))->setTimezone(new DateTimeZone('UTC'));}catch(Throwable){throw new InvalidArgumentException('A valid UTC date is required.');}}
    private function ageAt(string $dob,DateTimeImmutable $at):?int{if(trim($dob)==='')return null;try{$birth=new DateTimeImmutable($dob,new DateTimeZone('UTC'));}catch(Throwable){return null;}if($birth>$at)return null;return(int)$birth->diff($at)->y;}
    private function length(string $value):int{return function_exists('mb_strlen')?mb_strlen($value,'UTF-8'):strlen($value);}
    private function audit(int $competition,int $entry,string $action,array $metadata):void{$stmt=$this->pdo->prepare("INSERT dbo.competition_audit(competition_id,entry_id,submission_id,action_type,actor_type,actor_identifier,organization_code,succeeded,metadata_json) VALUES(:competition,:entry,NULL,:action,N'Student',NULL,NULL,1,:metadata)");$stmt->execute(['competition'=>$competition,'entry'=>$entry,'action'=>$action,'metadata'=>json_encode($metadata,JSON_THROW_ON_ERROR|JSON_UNESCAPED_SLASHES)]);}
}
