<?php
declare(strict_types=1);

final class SubscriptionEntitlementService {
    public function __construct(private PDO $db) {}

    public function resolve(string $yuvaId): array {
        $student=$this->student($yuvaId);
        $sql="SELECT TOP 1 p.plan_code,p.display_name,e.source_type,e.starts_at,e.ends_at,e.entitlement_guid
              FROM dbo.student_entitlements e JOIN dbo.subscription_plans p ON p.id=e.plan_id
              WHERE e.student_id=:student_id AND e.status=N'active' AND e.starts_at<=SYSUTCDATETIME()
                AND (e.ends_at IS NULL OR e.ends_at>SYSUTCDATETIME())
              ORDER BY p.priority DESC,COALESCE(e.ends_at,CONVERT(datetime2,'9999-12-31')) DESC,e.id DESC";
        $stmt=$this->db->prepare($sql);$stmt->execute(['student_id'=>$student['id']]);$row=$stmt->fetch(PDO::FETCH_ASSOC);
        if(!$row){return ['yuva_id'=>$student['yuva_id'],'plan_code'=>'free','display_name'=>'Free','source_type'=>'default','starts_at'=>null,'ends_at'=>null,'entitlement_guid'=>null];}
        return ['yuva_id'=>$student['yuva_id'],'plan_code'=>strtolower((string)$row['plan_code']),'display_name'=>(string)$row['display_name'],'source_type'=>(string)$row['source_type'],'starts_at'=>$row['starts_at'],'ends_at'=>$row['ends_at'],'entitlement_guid'=>(string)$row['entitlement_guid']];
    }

    public function hasFeature(string $yuvaId,string $featureKey): bool {
        $plan=$this->resolve($yuvaId);
        $stmt=$this->db->prepare("SELECT TOP 1 r.is_enabled FROM dbo.subscription_plans p JOIN dbo.plan_feature_versions v ON v.plan_id=p.id AND v.status=N'active' JOIN dbo.plan_feature_rules r ON r.feature_version_id=v.id WHERE p.plan_code=:plan AND r.feature_key=:feature ORDER BY v.version_number DESC");
        $stmt->execute(['plan'=>$plan['plan_code'],'feature'=>$featureKey]);return (bool)$stmt->fetchColumn();
    }

    public function campaigns(): array {return $this->db->query("SELECT campaign_guid,campaign_code,display_name,status,starts_at,ends_at,entitlement_duration_days,max_redemptions,(SELECT COUNT(*) FROM dbo.promo_campaign_participants x WHERE x.campaign_id=c.id) redeemed_count FROM dbo.promo_campaigns c ORDER BY created_at DESC")->fetchAll(PDO::FETCH_ASSOC);}
    public function invitations(): array {return $this->db->query("SELECT i.invitation_guid,c.campaign_code,s.yuva_id,i.code_hint,i.expires_at,i.used_at,i.revoked_at FROM dbo.promo_invitations i JOIN dbo.promo_campaigns c ON c.id=i.campaign_id JOIN dbo.students s ON s.id=i.intended_student_id ORDER BY i.created_at DESC")->fetchAll(PDO::FETCH_ASSOC);}
    public function activeEntitlements(): array {return $this->db->query("SELECT e.entitlement_guid,s.yuva_id,p.display_name,e.source_type,e.starts_at,e.ends_at FROM dbo.student_entitlements e JOIN dbo.students s ON s.id=e.student_id JOIN dbo.subscription_plans p ON p.id=e.plan_id WHERE e.status=N'active' ORDER BY e.created_at DESC")->fetchAll(PDO::FETCH_ASSOC);}
    public function auditHistory(): array {return $this->db->query("SELECT TOP 100 action_type,actor_role,entity_type,entity_reference,succeeded,created_at FROM dbo.subscription_audit ORDER BY id DESC")->fetchAll(PDO::FETCH_ASSOC);}

    public function createCampaign(array $actor,array $input): array {
        $this->master($actor);$code=strtoupper(trim((string)($input['campaign_code']??'')));$name=trim((string)($input['display_name']??''));
        if(!preg_match('/^[A-Z0-9][A-Z0-9-]{2,39}$/',$code)||$name===''||mb_strlen($name)>140)throw new InvalidArgumentException('Invalid campaign.');
        $stmt=$this->db->prepare("INSERT dbo.promo_campaigns(campaign_code,display_name,status,starts_at,ends_at,entitlement_duration_days,max_redemptions,created_by_email) OUTPUT CONVERT(nvarchar(36),INSERTED.campaign_guid) AS campaign_guid,INSERTED.id VALUES(:code,:name,N'draft',:starts,:ends,:duration,:max,:email)");
        $stmt->execute(['code'=>$code,'name'=>$name,'starts'=>$this->date($input['starts_at']??null),'ends'=>$this->date($input['ends_at']??null),'duration'=>max(1,min(730,(int)($input['entitlement_duration_days']??90))),'max'=>max(1,(int)($input['max_redemptions']??1)),'email'=>strtolower((string)$actor['email'])]);$row=$stmt->fetch(PDO::FETCH_ASSOC);$this->audit($actor,'CampaignCreated','campaign',(string)$row['campaign_guid'],true);return $row;
    }

    public function setCampaignStatus(array $actor,string $guid,string $status): void {$this->master($actor);if(!in_array($status,['active','disabled'],true))throw new InvalidArgumentException('Invalid status.');$stmt=$this->db->prepare("UPDATE dbo.promo_campaigns SET status=:status,updated_at=SYSUTCDATETIME() WHERE campaign_guid=:guid");$stmt->execute(['status'=>$status,'guid'=>$guid]);if($stmt->rowCount()!==1)throw new RuntimeException('Campaign not found.');$this->audit($actor,'CampaignStatusChanged','campaign',$guid,true,['status'=>$status]);}

    public function issueInvitation(array $actor,string $campaignGuid,string $yuvaId): array {
        $this->master($actor);$student=$this->student($yuvaId);$raw='YUVA-BETA-'.strtoupper(bin2hex(random_bytes(12)));$hex=hash('sha256',$raw);
        $this->db->beginTransaction();try{$stmt=$this->db->prepare("SELECT id FROM dbo.promo_campaigns WITH(UPDLOCK,HOLDLOCK) WHERE campaign_guid=:guid AND status=N'active' AND starts_at<=SYSUTCDATETIME() AND (ends_at IS NULL OR ends_at>SYSUTCDATETIME())");$stmt->execute(['guid'=>$campaignGuid]);$campaignId=$stmt->fetchColumn();if(!$campaignId)throw new RuntimeException('Campaign unavailable.');
            $stmt=$this->db->prepare("INSERT dbo.promo_invitations(campaign_id,intended_student_id,token_hash,code_hint,expires_at,created_by_email) VALUES(:campaign,:student,CONVERT(binary(32),:hash,2),:hint,DATEADD(hour,72,SYSUTCDATETIME()),:email)");$stmt->execute(['campaign'=>$campaignId,'student'=>$student['id'],'hash'=>$hex,'hint'=>substr($raw,-6),'email'=>strtolower((string)$actor['email'])]);$this->audit($actor,'InvitationIssued','student',$student['yuva_id'],true,['campaign_id'=>(int)$campaignId]);$this->db->commit();return ['invitation_code'=>$raw,'expires_in_hours'=>72];}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    public function redeem(string $yuvaId,string $rawToken): array {
        $student=$this->student($yuvaId);$hex=hash('sha256',trim($rawToken));$this->db->beginTransaction();try{$stmt=$this->db->prepare("SELECT TOP 1 i.id invitation_id,i.campaign_id,c.campaign_code,c.max_redemptions,c.entitlement_duration_days FROM dbo.promo_invitations i WITH(UPDLOCK,HOLDLOCK) JOIN dbo.promo_campaigns c WITH(UPDLOCK,HOLDLOCK) ON c.id=i.campaign_id WHERE i.token_hash=CONVERT(binary(32),:hash,2) AND i.intended_student_id=:student AND i.used_at IS NULL AND i.revoked_at IS NULL AND i.expires_at>SYSUTCDATETIME() AND c.status=N'active' AND c.starts_at<=SYSUTCDATETIME() AND (c.ends_at IS NULL OR c.ends_at>SYSUTCDATETIME())");$stmt->execute(['hash'=>$hex,'student'=>$student['id']]);$invite=$stmt->fetch(PDO::FETCH_ASSOC);if(!$invite)throw new RuntimeException('Invitation unavailable.');
            $blocked=$this->db->prepare("SELECT 1 FROM dbo.subscription_access_restrictions WHERE student_id=:student AND restriction_type=N'promo_redemption_block' AND lifted_at IS NULL AND (campaign_id IS NULL OR campaign_id=:campaign)");$blocked->execute(['student'=>$student['id'],'campaign'=>$invite['campaign_id']]);if($blocked->fetchColumn())throw new RuntimeException('Invitation unavailable.');
            $count=$this->db->prepare("SELECT COUNT(*) FROM dbo.promo_campaign_participants WHERE campaign_id=:campaign");$count->execute(['campaign'=>$invite['campaign_id']]);if((int)$count->fetchColumn()>=(int)$invite['max_redemptions'])throw new RuntimeException('Invitation unavailable.');
            $planId=$this->db->query("SELECT id FROM dbo.subscription_plans WHERE plan_code=N'premium'")->fetchColumn();$stmt=$this->db->prepare("INSERT dbo.student_entitlements(student_id,plan_id,source_type,source_reference,status,starts_at,ends_at,granted_by_email) OUTPUT CONVERT(nvarchar(36),INSERTED.entitlement_guid) AS entitlement_guid VALUES(:student,:plan,N'PREMIUM_BETA_PROMO',:source,N'active',SYSUTCDATETIME(),DATEADD(day,:duration,SYSUTCDATETIME()),N'self-service-redemption')");$stmt->execute(['student'=>$student['id'],'plan'=>$planId,'source'=>$invite['campaign_code'],'duration'=>(int)$invite['entitlement_duration_days']]);$ent=$stmt->fetch(PDO::FETCH_ASSOC);
            $this->db->prepare("UPDATE dbo.promo_invitations SET used_at=SYSUTCDATETIME() WHERE id=:id")->execute(['id'=>$invite['invitation_id']]);$this->db->prepare("INSERT dbo.promo_campaign_participants(campaign_id,student_id,invitation_id,entitlement_guid) VALUES(:campaign,:student,:invitation,:entitlement)")->execute(['campaign'=>$invite['campaign_id'],'student'=>$student['id'],'invitation'=>$invite['invitation_id'],'entitlement'=>$ent['entitlement_guid']]);$this->audit(['role'=>'Student','email'=>null,'yuva_id'=>$student['yuva_id']],'InvitationRedeemed','student',$student['yuva_id'],true);$this->db->commit();return $this->resolve($yuvaId);}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}
    }

    public function grantPremium(array $actor,string $yuvaId,?string $endsAt=null): array {$this->master($actor);$student=$this->student($yuvaId);$plan=$this->db->query("SELECT id FROM dbo.subscription_plans WHERE plan_code=N'premium'")->fetchColumn();$stmt=$this->db->prepare("INSERT dbo.student_entitlements(student_id,plan_id,source_type,status,starts_at,ends_at,granted_by_email) OUTPUT CONVERT(nvarchar(36),INSERTED.entitlement_guid) AS entitlement_guid VALUES(:student,:plan,N'PREMIUM_MANUAL',N'active',SYSUTCDATETIME(),:ends,:email)");$stmt->execute(['student'=>$student['id'],'plan'=>$plan,'ends'=>$this->date($endsAt),'email'=>strtolower((string)$actor['email'])]);$row=$stmt->fetch(PDO::FETCH_ASSOC);$this->audit($actor,'PremiumGranted','student',$student['yuva_id'],true);return $row;}
    public function revoke(array $actor,string $guid,bool $block=false): void {$this->master($actor);$this->db->beginTransaction();try{$find=$this->db->prepare("SELECT e.student_id,c.id campaign_id FROM dbo.student_entitlements e WITH(UPDLOCK,HOLDLOCK) LEFT JOIN dbo.promo_campaigns c ON c.campaign_code=e.source_reference WHERE e.entitlement_guid=:guid AND e.status=N'active'");$find->execute(['guid'=>$guid]);$record=$find->fetch(PDO::FETCH_ASSOC);if(!$record)throw new RuntimeException('Entitlement not found.');$stmt=$this->db->prepare("UPDATE dbo.student_entitlements SET status=N'revoked',revoked_at=SYSUTCDATETIME(),revoked_by_email=:email WHERE entitlement_guid=:guid AND status=N'active'");$stmt->execute(['email'=>strtolower((string)$actor['email']),'guid'=>$guid]);if($stmt->rowCount()!==1)throw new RuntimeException('Entitlement changed concurrently.');if($block){if(empty($record['campaign_id']))throw new RuntimeException('Only promotional access can be campaign-blocked.');$this->db->prepare("INSERT dbo.subscription_access_restrictions(student_id,campaign_id,restriction_type,reason,created_by_email) VALUES(:student,:campaign,N'promo_redemption_block',N'Master Admin revocation block',:email)")->execute(['student'=>$record['student_id'],'campaign'=>$record['campaign_id'],'email'=>strtolower((string)$actor['email'])]);}$this->audit($actor,'PremiumRevoked','entitlement',$guid,true,['block_future_redemption'=>$block]);$this->db->commit();}catch(Throwable $e){if($this->db->inTransaction())$this->db->rollBack();throw $e;}}

    private function student(string $yuvaId): array {$stmt=$this->db->prepare("SELECT id,yuva_id FROM dbo.students WHERE UPPER(yuva_id)=UPPER(:yuva)");$stmt->execute(['yuva'=>trim($yuvaId)]);$row=$stmt->fetch(PDO::FETCH_ASSOC);if(!$row)throw new RuntimeException('Student not found.');return $row;}
    private function master(array $actor): void {if(($actor['role']??'')!==YUVA_ROLE_MASTER_ADMIN)throw new RuntimeException('Not authorized.');}
    private function date(mixed $v): ?string {$v=trim((string)$v);return $v===''?null:str_replace('T',' ',$v);}
    private function audit(array $actor,string $action,string $entity,string $ref,bool $success,array $metadata=[]): void {$stmt=$this->db->prepare("INSERT dbo.subscription_audit(action_type,actor_role,actor_identifier,entity_type,entity_reference,succeeded,metadata_json) VALUES(:action,:role,:actor,:entity,:reference,:success,:metadata)");$stmt->execute(['action'=>$action,'role'=>(string)($actor['role']??'System'),'actor'=>(string)($actor['email']??$actor['yuva_id']??''),'entity'=>$entity,'reference'=>$ref,'success'=>$success?1:0,'metadata'=>$metadata===[]?null:json_encode($metadata,JSON_THROW_ON_ERROR)]);}
}
