SET XACT_ABORT ON;
BEGIN TRANSACTION;

IF OBJECT_ID(N'dbo.subscription_plans',N'U') IS NULL CREATE TABLE dbo.subscription_plans(
 id BIGINT IDENTITY PRIMARY KEY,plan_code NVARCHAR(30) NOT NULL UNIQUE,display_name NVARCHAR(80) NOT NULL,priority INT NOT NULL CONSTRAINT df_subscription_plan_priority DEFAULT 0,status NVARCHAR(20) NOT NULL CONSTRAINT df_subscription_plan_status DEFAULT N'active',created_at DATETIME2 NOT NULL CONSTRAINT df_subscription_plan_created DEFAULT SYSUTCDATETIME(),CONSTRAINT ck_subscription_plan_status CHECK(status IN(N'active',N'inactive')));
IF OBJECT_ID(N'dbo.plan_feature_versions',N'U') IS NULL CREATE TABLE dbo.plan_feature_versions(
 id BIGINT IDENTITY PRIMARY KEY,plan_id BIGINT NOT NULL,version_number INT NOT NULL,status NVARCHAR(20) NOT NULL,starts_at DATETIME2 NOT NULL CONSTRAINT df_plan_feature_version_start DEFAULT SYSUTCDATETIME(),created_at DATETIME2 NOT NULL CONSTRAINT df_plan_feature_version_created DEFAULT SYSUTCDATETIME(),CONSTRAINT fk_plan_feature_plan FOREIGN KEY(plan_id) REFERENCES dbo.subscription_plans(id),CONSTRAINT uq_plan_feature_version UNIQUE(plan_id,version_number),CONSTRAINT ck_plan_feature_version_status CHECK(status IN(N'draft',N'active',N'retired')));
IF OBJECT_ID(N'dbo.plan_feature_rules',N'U') IS NULL CREATE TABLE dbo.plan_feature_rules(
 id BIGINT IDENTITY PRIMARY KEY,feature_version_id BIGINT NOT NULL,feature_key NVARCHAR(80) NOT NULL,is_enabled BIT NOT NULL,policy_json NVARCHAR(MAX) NULL,CONSTRAINT fk_plan_feature_rule_version FOREIGN KEY(feature_version_id) REFERENCES dbo.plan_feature_versions(id),CONSTRAINT uq_plan_feature_rule UNIQUE(feature_version_id,feature_key),CONSTRAINT ck_plan_feature_rule_json CHECK(policy_json IS NULL OR ISJSON(policy_json)=1));
IF OBJECT_ID(N'dbo.student_entitlements',N'U') IS NULL CREATE TABLE dbo.student_entitlements(
 id BIGINT IDENTITY PRIMARY KEY,entitlement_guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT df_student_entitlement_guid DEFAULT NEWID() UNIQUE,student_id BIGINT NOT NULL,plan_id BIGINT NOT NULL,source_type NVARCHAR(60) NOT NULL,source_reference NVARCHAR(190) NULL,status NVARCHAR(20) NOT NULL CONSTRAINT df_student_entitlement_status DEFAULT N'active',starts_at DATETIME2 NOT NULL,ends_at DATETIME2 NULL,granted_by_email NVARCHAR(190) NULL,revoked_at DATETIME2 NULL,revoked_by_email NVARCHAR(190) NULL,created_at DATETIME2 NOT NULL CONSTRAINT df_student_entitlement_created DEFAULT SYSUTCDATETIME(),row_version ROWVERSION NOT NULL,CONSTRAINT fk_student_entitlement_student FOREIGN KEY(student_id) REFERENCES dbo.students(id),CONSTRAINT fk_student_entitlement_plan FOREIGN KEY(plan_id) REFERENCES dbo.subscription_plans(id),CONSTRAINT ck_student_entitlement_status CHECK(status IN(N'active',N'revoked',N'expired')),CONSTRAINT ck_student_entitlement_dates CHECK(ends_at IS NULL OR starts_at<ends_at));
IF OBJECT_ID(N'dbo.promo_campaigns',N'U') IS NULL CREATE TABLE dbo.promo_campaigns(
 id BIGINT IDENTITY PRIMARY KEY,campaign_guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT df_promo_campaign_guid DEFAULT NEWID() UNIQUE,campaign_code NVARCHAR(40) NOT NULL UNIQUE,display_name NVARCHAR(140) NOT NULL,status NVARCHAR(20) NOT NULL CONSTRAINT df_promo_campaign_status DEFAULT N'draft',starts_at DATETIME2 NULL,ends_at DATETIME2 NULL,entitlement_duration_days SMALLINT NOT NULL CONSTRAINT df_promo_campaign_duration DEFAULT 90,max_redemptions INT NOT NULL,created_by_email NVARCHAR(190) NOT NULL,created_at DATETIME2 NOT NULL CONSTRAINT df_promo_campaign_created DEFAULT SYSUTCDATETIME(),updated_at DATETIME2 NOT NULL CONSTRAINT df_promo_campaign_updated DEFAULT SYSUTCDATETIME(),row_version ROWVERSION NOT NULL,CONSTRAINT ck_promo_campaign_status CHECK(status IN(N'draft',N'active',N'disabled')),CONSTRAINT ck_promo_campaign_limit CHECK(max_redemptions>0),CONSTRAINT ck_promo_campaign_duration CHECK(entitlement_duration_days BETWEEN 1 AND 730),CONSTRAINT ck_promo_campaign_dates CHECK(ends_at IS NULL OR starts_at IS NULL OR starts_at<ends_at));
IF OBJECT_ID(N'dbo.promo_invitations',N'U') IS NULL CREATE TABLE dbo.promo_invitations(
 id BIGINT IDENTITY PRIMARY KEY,invitation_guid UNIQUEIDENTIFIER NOT NULL CONSTRAINT df_promo_invitation_guid DEFAULT NEWID() UNIQUE,campaign_id BIGINT NOT NULL,intended_student_id BIGINT NOT NULL,token_hash BINARY(32) NOT NULL UNIQUE,code_hint CHAR(6) NOT NULL,expires_at DATETIME2 NOT NULL,used_at DATETIME2 NULL,revoked_at DATETIME2 NULL,created_by_email NVARCHAR(190) NOT NULL,created_at DATETIME2 NOT NULL CONSTRAINT df_promo_invitation_created DEFAULT SYSUTCDATETIME(),CONSTRAINT fk_promo_invitation_campaign FOREIGN KEY(campaign_id) REFERENCES dbo.promo_campaigns(id),CONSTRAINT fk_promo_invitation_student FOREIGN KEY(intended_student_id) REFERENCES dbo.students(id));
IF OBJECT_ID(N'dbo.promo_campaign_participants',N'U') IS NULL CREATE TABLE dbo.promo_campaign_participants(
 id BIGINT IDENTITY PRIMARY KEY,campaign_id BIGINT NOT NULL,student_id BIGINT NOT NULL,invitation_id BIGINT NOT NULL,entitlement_guid UNIQUEIDENTIFIER NOT NULL,redeemed_at DATETIME2 NOT NULL CONSTRAINT df_promo_participant_redeemed DEFAULT SYSUTCDATETIME(),CONSTRAINT fk_promo_participant_campaign FOREIGN KEY(campaign_id) REFERENCES dbo.promo_campaigns(id),CONSTRAINT fk_promo_participant_student FOREIGN KEY(student_id) REFERENCES dbo.students(id),CONSTRAINT fk_promo_participant_invitation FOREIGN KEY(invitation_id) REFERENCES dbo.promo_invitations(id),CONSTRAINT fk_promo_participant_entitlement FOREIGN KEY(entitlement_guid) REFERENCES dbo.student_entitlements(entitlement_guid),CONSTRAINT uq_promo_participant UNIQUE(campaign_id,student_id),CONSTRAINT uq_promo_participant_invitation UNIQUE(invitation_id));
IF OBJECT_ID(N'dbo.subscription_access_restrictions',N'U') IS NULL CREATE TABLE dbo.subscription_access_restrictions(
 id BIGINT IDENTITY PRIMARY KEY,student_id BIGINT NOT NULL,campaign_id BIGINT NULL,restriction_type NVARCHAR(60) NOT NULL,reason NVARCHAR(500) NOT NULL,created_by_email NVARCHAR(190) NOT NULL,created_at DATETIME2 NOT NULL CONSTRAINT df_subscription_restriction_created DEFAULT SYSUTCDATETIME(),lifted_at DATETIME2 NULL,lifted_by_email NVARCHAR(190) NULL,CONSTRAINT fk_subscription_restriction_student FOREIGN KEY(student_id) REFERENCES dbo.students(id),CONSTRAINT fk_subscription_restriction_campaign FOREIGN KEY(campaign_id) REFERENCES dbo.promo_campaigns(id),CONSTRAINT ck_subscription_restriction_type CHECK(restriction_type IN(N'promo_redemption_block',N'feature_access_suspension')));
IF OBJECT_ID(N'dbo.subscription_audit',N'U') IS NULL CREATE TABLE dbo.subscription_audit(
 id BIGINT IDENTITY PRIMARY KEY,action_type NVARCHAR(80) NOT NULL,actor_role NVARCHAR(40) NOT NULL,actor_identifier NVARCHAR(190) NULL,entity_type NVARCHAR(40) NOT NULL,entity_reference NVARCHAR(190) NULL,succeeded BIT NOT NULL,metadata_json NVARCHAR(MAX) NULL,created_at DATETIME2 NOT NULL CONSTRAINT df_subscription_audit_created DEFAULT SYSUTCDATETIME(),CONSTRAINT ck_subscription_audit_json CHECK(metadata_json IS NULL OR ISJSON(metadata_json)=1));

IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.student_entitlements') AND name=N'idx_student_entitlements_effective') EXEC(N'CREATE INDEX idx_student_entitlements_effective ON dbo.student_entitlements(student_id,status,starts_at,ends_at) INCLUDE(plan_id,source_type,entitlement_guid);');
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.promo_invitations') AND name=N'idx_promo_invitations_student') EXEC(N'CREATE INDEX idx_promo_invitations_student ON dbo.promo_invitations(intended_student_id,campaign_id,expires_at);');
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.promo_invitations') AND name=N'uq_promo_invitations_pending_student') EXEC(N'CREATE UNIQUE INDEX uq_promo_invitations_pending_student ON dbo.promo_invitations(campaign_id,intended_student_id) WHERE used_at IS NULL AND revoked_at IS NULL;');
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.subscription_access_restrictions') AND name=N'idx_subscription_restrictions_active') EXEC(N'CREATE INDEX idx_subscription_restrictions_active ON dbo.subscription_access_restrictions(student_id,campaign_id,restriction_type,lifted_at);');

IF NOT EXISTS(SELECT 1 FROM dbo.subscription_plans WHERE plan_code=N'free') INSERT dbo.subscription_plans(plan_code,display_name,priority) VALUES(N'free',N'Free',0);
IF NOT EXISTS(SELECT 1 FROM dbo.subscription_plans WHERE plan_code=N'premium') INSERT dbo.subscription_plans(plan_code,display_name,priority) VALUES(N'premium',N'Premium',100);
DECLARE @free BIGINT=(SELECT id FROM dbo.subscription_plans WHERE plan_code=N'free'),@premium BIGINT=(SELECT id FROM dbo.subscription_plans WHERE plan_code=N'premium');
IF NOT EXISTS(SELECT 1 FROM dbo.plan_feature_versions WHERE plan_id=@free AND version_number=1) INSERT dbo.plan_feature_versions(plan_id,version_number,status) VALUES(@free,1,N'active');
IF NOT EXISTS(SELECT 1 FROM dbo.plan_feature_versions WHERE plan_id=@premium AND version_number=1) INSERT dbo.plan_feature_versions(plan_id,version_number,status) VALUES(@premium,1,N'active');
DECLARE @fv BIGINT=(SELECT id FROM dbo.plan_feature_versions WHERE plan_id=@free AND version_number=1),@pv BIGINT=(SELECT id FROM dbo.plan_feature_versions WHERE plan_id=@premium AND version_number=1);
IF NOT EXISTS(SELECT 1 FROM dbo.plan_feature_rules WHERE feature_version_id=@fv) INSERT dbo.plan_feature_rules(feature_version_id,feature_key,is_enabled,policy_json) VALUES(@fv,N'ai_research',1,N'{"enforced":false}'),(@fv,N'ai_document',1,N'{"enforced":false}'),(@fv,N'ai_media',1,N'{"enforced":false}'),(@fv,N'practice_advanced',1,N'{"enforced":false}');
IF NOT EXISTS(SELECT 1 FROM dbo.plan_feature_rules WHERE feature_version_id=@pv) INSERT dbo.plan_feature_rules(feature_version_id,feature_key,is_enabled,policy_json) VALUES(@pv,N'ai_research',1,N'{"enforced":false}'),(@pv,N'ai_document',1,N'{"enforced":false}'),(@pv,N'ai_media',1,N'{"enforced":false}'),(@pv,N'practice_advanced',1,N'{"enforced":false}');
COMMIT TRANSACTION;
