<?php
declare(strict_types=1);
require __DIR__.'/../../backend/config.php';
require __DIR__.'/../../backend/delivery/MediaRetentionService.php';
use YuvaClub\Delivery\MediaRetentionService;
function checkRetention(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);echo "PASS $message\n";}
function writeMedia(string $root,string $id,string $name,string $body):array{$dir=$root.DIRECTORY_SEPARATOR.$id.DIRECTORY_SEPARATOR.'media';mkdir($dir,0700,true);$path=$dir.DIRECTORY_SEPARATOR.$name;file_put_contents($path,$body);return[$path,hash('sha256',$body)];}
function metadata(string $file,array $records):void{file_put_contents($file,json_encode($records,JSON_PRETTY_PRINT));}
$root=sys_get_temp_dir().DIRECTORY_SEPARATOR.'yuva-retention-'.bin2hex(random_bytes(5));mkdir($root,0700,true);$meta=$root.DIRECTORY_SEPARATOR.'presentation-media.json';$now=new DateTimeImmutable('2026-08-19T12:00:00Z');$audits=[];$processing=[];
$make=function(string $id,string $name,int $age,string $body='media')use($root,$now):array{[$path,$sha]=writeMedia($root,$id,$name,$body);return['path'=>$path,'record'=>['stored_filename'=>$name,'media_reference'=>$id.'/media/'.$name,'sha256'=>$sha,'uploaded_at'=>$now->modify("-$age days")->format(DATE_ATOM),'retention_status'=>'Active']];};
$m29=$make('YC2026901','29.mp3',29,'29');$m30=$make('YC2026902','30.mp3',30,'30');$m31=$make('YC2026903','31.mp3',31,'31');
metadata($meta,['YC2026901'=>$m29['record'],'YC2026902'=>$m30['record'],'YC2026903'=>$m31['record']]);
$factory=function(?callable $delete=null)use($meta,$root,&$audits,&$processing,$now):MediaRetentionService{return new MediaRetentionService($meta,$root,fn(string $id):bool=>str_starts_with($id,'YC2026'),fn(string $id,string $ref):bool=>in_array($ref,$processing,true),function(array $row)use(&$audits):void{$audits[]=$row;},$delete,fn()=>$now);};
$dry=$factory()->run(30,true,'dry');checkRetention($dry['eligible']===2&&$dry['deleted']===0,'dry-run identifies eligible media without deletion');checkRetention(is_file($m30['path'])&&is_file($m31['path']),'dry-run deletes nothing');
$run=$factory()->run(30,false,'execute');checkRetention(is_file($m29['path']),'29-day media is preserved');checkRetention(!is_file($m30['path']),'exactly 30-day media is deleted');checkRetention(!is_file($m31['path']),'older-than-30-day media is deleted');checkRetention($run['deleted']===2,'eligible batch count is exact');
$rerun=$factory()->run(30,false,'repeat');checkRetention($rerun['deleted']===0&&count($audits)===2,'rerun is idempotent without duplicate side effects');
$disabled=$make('YC2026904','disabled.mp3',90,'disabled');metadata($meta,['YC2026904'=>$disabled['record']]);checkRetention($factory()->run(0,false,'zero')['status']==='disabled'&&is_file($disabled['path']),'zero retention performs no deletion');checkRetention($factory()->run(null,false,'missing')['status']==='disabled'&&is_file($disabled['path']),'missing retention performs no deletion');
putenv('YUVA_MEDIA_RETENTION_DAYS=invalid');checkRetention(env_positive_int('YUVA_MEDIA_RETENTION_DAYS')===null,'invalid retention configuration fails closed');putenv('YUVA_MEDIA_RETENTION_DAYS');
$manual=$make('YC2026905','manual.mp3',90,'manual');unlink($manual['path']);$manual['record']['retention_status']='StudentDeleted';$new=$make('YC2026906','new.mp3',5,'new');metadata($meta,['YC2026905'=>$manual['record'],'YC2026906'=>$new['record']]);checkRetention($factory()->run(30,false,'manual')['deleted']===0&&is_file($new['path']),'manual deletion and replacement rerun are safe');
$proc=$make('YC2026907','processing.mp3',90,'processing');metadata($meta,['YC2026907'=>$proc['record']]);$processing=[$proc['record']['media_reference']];checkRetention($factory()->run(30,false,'processing')['deleted']===0&&is_file($proc['path']),'Processing media is preserved');$processing=[];
$evidence=['applied_review'=>'kept','transcript'=>'kept','metrics'=>'kept','consent'=>'kept','tokens'=>4,'official_rubric'=>91];$eligible=$make('YC2026908','evidence.mp3',31,'evidence');metadata($meta,['YC2026908'=>$eligible['record']]);$before=$evidence;$factory()->run(30,false,'evidence');checkRetention($evidence===$before,'Applied review transcript metrics consent token and rubric evidence remain');
$cross=$make('YC2026909','cross.mp3',31,'cross');$cross['record']['media_reference']='YC2026999/media/cross.mp3';$trav=$make('YC2026910','travel.mp3',31,'travel');$trav['record']['stored_filename']='../travel.mp3';metadata($meta,['YC2026909'=>$cross['record'],'YC2026910'=>$trav['record']]);$rejected=$factory()->run(30,false,'paths');checkRetention($rejected['deleted']===0&&is_file($cross['path'])&&is_file($trav['path']),'cross-student and traversal paths are rejected');
$failure=$make('YC2026911','failure.mp3',31,'failure');metadata($meta,['YC2026911'=>$failure['record']]);$failed=$factory(fn(string $path):bool=>false)->run(30,false,'failure');$afterFailure=json_decode((string)file_get_contents($meta),true);checkRetention($failed['failed']===1&&is_file($failure['path'])&&($afterFailure['YC2026911']['retention_status']??'')==='Active','physical deletion failure is retryable and not falsely tombstoned');
$serviceSource=file_get_contents(__DIR__.'/../../backend/delivery/MediaRetentionService.php');$runnerSource=file_get_contents(__DIR__.'/../../tools/media-retention.php');$webJobSource=file_get_contents(__DIR__.'/../../App_Data/jobs/triggered/yuva-media-retention/run.php');$job=json_decode((string)file_get_contents(__DIR__.'/../../App_Data/jobs/triggered/yuva-media-retention/settings.job'),true);checkRetention(!str_contains($serviceSource,'transcript')&&!str_contains($serviceSource,'OPENAI_API_KEY')&&!str_contains($runnerSource,'DB_PASSWORD'),'retention logs and runner exclude secrets and media contents');checkRetention(PHP_SAPI==='cli'&&str_contains($runnerSource,"PHP_SAPI !== 'cli'"),'retention runner is CLI-only');checkRetention(str_contains($webJobSource,"\$argv[] = '--execute'"),'scheduled WebJob executes retention enforcement');checkRetention(($job['schedule']??'')==='0 15 3 * * *'&&($job['is_singleton']??false)===true,'daily scheduler is singleton');
$iterator=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($root,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($iterator as $item){$item->isDir()?rmdir($item->getPathname()):unlink($item->getPathname());}rmdir($root);
echo "AI Mentor media retention tests: PASS\n";
