<?php
declare(strict_types=1);
function quick_check(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);}
$root=dirname(__DIR__,2);$migration=(string)file_get_contents($root.'/database/16-quick-challenges-phase2c2a.azure-sql.sql');$rollback=(string)file_get_contents($root.'/database/16-quick-challenges-phase2c2a-rollback.sql');$service=(string)file_get_contents($root.'/backend/quick-challenge.php');$admin=(string)file_get_contents($root.'/admin-quick-challenge-action.php');$start=(string)file_get_contents($root.'/student-quick-challenge-start.php');$submit=(string)file_get_contents($root.'/student-quick-challenge-submit.php');$panel=(string)file_get_contents($root.'/quick-challenge-admin-panel.php');$portal=(string)file_get_contents($root.'/portal.php');
foreach(['quick_challenge_skills','quick_challenge_templates','quick_challenge_template_versions','quick_challenge_template_version_skills','quick_challenge_attempts','student_challenge_personal_bests']as$table)quick_check(str_contains($migration,"dbo.$table"),'Migration 16 missing '.$table);
foreach(['quick_template_version_id','experience_mode','quick_practice','quick_ranked','ROWVERSION','response_deadline_at','source_revision_hash','source_snapshot_json','score_version','best_attempt_id']as$contract)quick_check(str_contains($migration,$contract),'Migration 16 contract missing '.$contract);
foreach(['public-speaking','storytelling','persuasion','research','critical-thinking','impromptu-speaking','presentation-delivery','communication-clarity','leadership','teaching']as$skill)quick_check(str_contains($migration,$skill),'Skill catalog missing '.$skill);
quick_check(str_contains($migration,"OBJECT_ID(N'dbo.quick_challenge_templates', N'U') IS NULL")&&str_contains($migration,'COL_LENGTH')&&str_contains($migration,'sys.indexes'),'Migration 16 must be guarded and idempotent.');
quick_check(str_contains($migration,"EXEC(N'CREATE INDEX")&&str_contains($migration,'uq_quick_challenge_attempt_number'),'Same-batch column indexes and uniqueness guards are required.');
quick_check(str_contains($rollback,"DB_NAME() NOT LIKE N'%rehearsal%'")&&str_contains($rollback,"DROP TABLE IF EXISTS dbo.quick_challenge_attempts")&&!str_contains($rollback,"DROP TABLE dbo.competitions"),'Rollback must be rehearsal-only and additive.');
foreach(['Master Admin authorization is required','Challenge manager scope was rejected','known active organization','Active same-organization membership is required','Attempt limit reached','Quick Challenge timing window has closed','Stale or duplicate attempt submission was rejected','SERIALIZABLE','db_acquire_application_lock','CONVERT(BINARY(8),:version,2)','normalize_sqlsrv_rowversion_token']as$contract)quick_check(str_contains($service.$admin,$contract),'Service/security contract missing '.$contract);
quick_check(str_contains($service,"hash('sha256',\$snapshot)")&&str_contains($service,"[status]=N'Submitted'")&&str_contains($service,'source_snapshot_json'),'Submission must freeze a canonical snapshot and hash.');
quick_check(!str_contains($service,'$foundation->join')&&str_contains($service,'INSERT dbo.competition_entries')&&str_contains($service,"},'SERIALIZABLE',true)"),'Entry and first attempt must share one rollback-safe serializable transaction.');
quick_check(str_contains($service,'attempt.student_id=:student')&&str_contains($service,'entry.student_id=:student_owner'),'Attempt ownership must be student scoped.');
quick_check(str_contains($service,'practice_score IS NULL')&&str_contains($service,'student_challenge_personal_bests')&&str_contains($service,'score_version'),'Practice score and versioned personal-best foundation missing.');
quick_check(!str_contains($service,'leadership_decisions')&&!str_contains($service,'current_level_id'),'Quick Challenges must not promote leadership levels.');
quick_check(!str_contains($service,'competition_score')&&!str_contains($service,'leaderboard'),'Phase 2C.2B scoring/leaderboard is out of scope.');
quick_check(str_contains($rollback,'DROP INDEX idx_competitions_quick_template ON dbo.competitions'),'Rollback must remove its dependent index before dropping Migration 16 columns.');
foreach([$admin,$start,$submit]as$handler)quick_check(str_contains($handler,'require_admin_post')||str_contains($handler,'verify_csrf_token'),'Every mutation must enforce CSRF.');
quick_check(str_contains($start,'require_student()')&&str_contains($submit,'require_student()'),'Student mutations require authenticated student context.');
quick_check(str_contains($service,'MasterAdmin')&&str_contains($service,'OrganizationAdmin')&&str_contains($service,"Prompt revealed when you start."),'Required management and deferred prompt contract missing.');
quick_check(!preg_match('/student_email|parent_email|date_of_birth|phone|address/i',$panel.$portal),'Quick Challenge surfaces must not expose private identity fields.');
echo "Quick Challenges Phase 2C.2A contracts PASS\n";
